// payment-demo-vue/src/views/Account.vue
<template>
  <div class="tb-page"><div class="container">
    <h2 class="tb-h2">我的</h2>
    <div class="tb-cardbox m-quick">
      <router-link class="m-quick-item" to="/orders">📦 我的订单<span class="arrow">›</span></router-link>
      <router-link class="m-quick-item" to="/refund-applications">💸 我的退款申请<span class="arrow">›</span></router-link>
      <router-link class="m-quick-item" to="/cart">🛒 购物车<span class="arrow">›</span></router-link>
    </div>
    <div class="tb-cardbox" style="max-width:520px">
      <div class="tb-account-head">
        <div class="tb-account-avatar">{{(user && user.username ? user.username : 'U').slice(0, 1).toUpperCase()}}</div>
        <div>
          <div class="tb-account-name">{{user ? user.username : '-'}}</div>
          <div class="tb-account-role">{{user ? user.role : '-'}}</div>
        </div>
      </div>
      <el-form label-position="top">
        <el-form-item label="原密码"><el-input v-model="form.oldPassword" type="password" show-password /></el-form-item>
        <el-form-item label="新密码（至少8位）"><el-input v-model="form.newPassword" type="password" show-password /></el-form-item>
        <el-button type="primary" @click="changePassword">修改密码</el-button>
        <el-button @click="logout">退出登录</el-button>
      </el-form>
    </div>
    <p class="m-demo-note">淘支付商城 · 支付业务演示（支付宝 / 微信支付沙箱）<br/>仅供学习演示，请勿用于真实交易</p>
  </div></div>
</template>
<script>
import authApi from '../api/auth'
import { clearAuth, getRefreshToken, getUser } from '../utils/authStore'
export default {
  data() { return { user: getUser(), form: { oldPassword: '', newPassword: '' } } },
  methods: {
    async changePassword() { if (!this.form.oldPassword || !this.form.newPassword || this.form.newPassword.length < 8) return this.$message.error('请正确填写密码，新密码至少8位'); await authApi.changePassword(this.form); clearAuth(); this.$message.success('密码修改成功，请重新登录'); this.$router.replace('/login') },
    async logout() { try { await authApi.logout(getRefreshToken()) } finally { clearAuth(); this.$router.replace('/login') } }
  }
}
</script>

// user-ui/src/pages/Account.jsx
import { useState } from 'react'
import { Form, Input, message, Modal } from 'antd'
import { Link } from 'react-router-dom'
import authApi from '@/api/auth'
import { clearAuth, getRefreshToken } from '@/utils/authStore'

export default function Account(){
  const [pwdOpen, setPwdOpen] = useState(false)
  const [form] = Form.useForm()
  const openPwd = () => { form.resetFields(); setPwdOpen(true) }
  const change = async v => {
    await authApi.changePassword({ oldPassword: v.oldPassword, newPassword: v.newPassword })
    setPwdOpen(false)
    clearAuth()
    message.success('密码修改成功，请重新登录')
    location.hash = '#/login'
  }
  const doLogout = async () => { try { await authApi.logout(getRefreshToken()) } finally { clearAuth(); location.hash = '#/login' } }
  const confirmLogout = () => Modal.confirm({
    title: '退出登录',
    content: '是否确认登出？',
    okText: '确认',
    cancelText: '取消',
    onOk: doLogout
  })
  return <div className="tb-page">
    <div className="container">
      <h2 className="tb-h2">我的</h2>
      <div className="tb-cardbox m-quick">
        <Link className="m-quick-item" to="/orders">📦 我的订单<span className="arrow">›</span></Link>
        <Link className="m-quick-item" to="/refund-applications">💸 我的退款申请<span className="arrow">›</span></Link>
        <Link className="m-quick-item" to="/cart">🛒 购物车<span className="arrow">›</span></Link>
        <Link className="m-quick-item" to="/addresses">📍 收货地址<span className="arrow">›</span></Link>
        <button type="button" className="m-quick-item" onClick={openPwd}>🔑 修改密码<span className="arrow">›</span></button>
        <button type="button" className="m-quick-item" onClick={confirmLogout}>🚪 退出登录<span className="arrow">›</span></button>
      </div>
    </div>
    <Modal
      title="修改密码"
      open={pwdOpen}
      onCancel={() => setPwdOpen(false)}
      onOk={() => form.submit()}
      okText="确认修改"
      cancelText="取消"
      destroyOnHidden
      maskClosable={false}
    >
      <Form form={form} layout="vertical" onFinish={change}>
        <Form.Item label="原密码" name="oldPassword" rules={[{ required: true, message: '请输入原密码' }]}>
          <Input.Password placeholder="请输入原密码" />
        </Form.Item>
        <Form.Item label="新密码" name="newPassword" rules={[{ required: true, min: 8, message: '新密码至少8位' }]}>
          <Input.Password placeholder="请输入新密码（至少8位）" />
        </Form.Item>
        <Form.Item
          label="确认新密码"
          name="confirmPassword"
          dependencies={['newPassword']}
          rules={[
            { required: true, message: '请再次输入新密码' },
            ({ getFieldValue }) => ({
              validator(_, v) {
                return !v || v === getFieldValue('newPassword')
                  ? Promise.resolve()
                  : Promise.reject(new Error('两次输入的新密码不一致'))
              }
            })
          ]}
        >
          <Input.Password placeholder="请再次输入新密码" />
        </Form.Item>
      </Form>
    </Modal>
  </div>
}
