// payment-demo-vue/src/components/AppHeader.vue
<template>
  <header class="m-bar">
    <div class="m-bar-row">
      <router-link to="/" class="m-logo">
        <span>🛍️</span>
        <span class="m-logo-text">淘支付<small>演示商城</small></span>
      </router-link>
      <router-link v-if="loggedIn" to="/account" class="m-user">👋 {{ username }}</router-link>
      <router-link v-else to="/login" class="m-user">登录 / 注册</router-link>
    </div>
    <div class="m-search">
      <input v-model="kw" placeholder="搜索好物（演示入口，回车逛全店）" @keyup.enter="go('/')"/>
      <button @click="go('/')">搜索</button>
    </div>
  </header>
</template>
<script>
import { getAccessToken, getUser } from '../utils/authStore'
export default {
  data() { return { authTick: 0, kw: '' } },
  computed: {
    loggedIn() { this.authTick; return !!getAccessToken() },
    username() { this.authTick; const u = getUser(); return (u && u.username) || '我的' }
  },
  methods: {
    go(path) { this.$router.push(path).catch(() => {}) }
  },
  created() { this.listener = () => { this.authTick += 1 }; window.addEventListener('payment-auth-changed', this.listener) },
  beforeDestroy() { window.removeEventListener('payment-auth-changed', this.listener) }
}
</script>

// user-ui/src/components/AppHeader.jsx
import { Link, useNavigate } from 'react-router-dom'
import { getAccessToken, getUser } from '@/utils/authStore'

export default function AppHeader() {
  const navigate = useNavigate()
  const user = getUser()
  const loggedIn = Boolean(getAccessToken())
  return (
    <header className="m-bar">
      <div className="m-bar-row">
        <Link to="/" className="m-logo">
          <span>🛍️</span>
          <span className="m-logo-text">Mall</span>
        </Link>
        {loggedIn
          ? <Link to="/account" className="m-user">👋 {user?.username || '我的'}</Link>
          : <Link to="/login" className="m-user">登录 / 注册</Link>}
      </div>
      <div className="m-search">
        <input placeholder="搜索好物（演示入口，回车逛全店）" onKeyDown={e => { if (e.key === 'Enter') navigate('/') }} />
        <button onClick={() => navigate('/')}>搜索</button>
      </div>
    </header>
  )
}
