// payment-demo-vue-admin/src/views/PaymentConfig.vue
<template>
  <div>
    <h2 class="adm-page-title">支付配置</h2>

    <div class="adm-card">
      <el-tabs v-model="activeTab" type="border-card">
        <el-tab-pane label="支付渠道配置" name="channel">
          <div class="toolbar">
            <el-button type="primary" @click="openChannelDialog()">新增渠道</el-button>
            <el-button @click="loadChannels">刷新</el-button>
            <el-button type="primary" plain @click="reloadConfig">重新加载配置缓存</el-button>
          </div>
          <el-table :data="channelList" border style="width: 100%">
            <el-table-column type="index" width="50"></el-table-column>
            <el-table-column prop="channelName" label="渠道名称" width="140"></el-table-column>
            <el-table-column prop="channelCode" label="渠道编码" width="120"></el-table-column>
            <el-table-column label="状态" width="110">
              <template slot-scope="scope">
                <el-tag :type="scope.row.channelStatus === 'ENABLED' ? 'success' : 'info'">
                  {{ scope.row.channelStatus }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="channelDesc" label="描述"></el-table-column>
            <el-table-column prop="sortOrder" label="排序" width="80"></el-table-column>
            <el-table-column label="操作" width="260" align="center">
              <template slot-scope="scope">
                <el-button type="text" @click="openChannelDialog(scope.row)">编辑</el-button>
                <el-button type="text" @click="toggleChannelStatus(scope.row)">
                  {{ scope.row.channelStatus === 'ENABLED' ? '禁用' : '启用' }}
                </el-button>
                <el-button type="text" class="danger-btn" @click="deleteChannel(scope.row)">删除</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>

        <el-tab-pane label="支付应用配置" name="app">
          <div class="toolbar">
            <el-button type="primary" @click="openAppDialog()">新增应用</el-button>
            <el-button @click="loadApps">刷新</el-button>
            <el-button type="primary" plain @click="reloadConfig">重新加载配置缓存</el-button>
          </div>
          <el-table :data="appList" border style="width: 100%">
            <el-table-column type="index" width="50"></el-table-column>
            <el-table-column prop="appName" label="应用名称" width="170"></el-table-column>
            <el-table-column prop="appCode" label="应用编码" width="190"></el-table-column>
            <el-table-column prop="channelName" label="所属渠道" width="120"></el-table-column>
            <el-table-column label="状态" width="110">
              <template slot-scope="scope">
                <el-tag :type="scope.row.appStatus === 'ENABLED' ? 'success' : 'info'">
                  {{ scope.row.appStatus }}
                </el-tag>
              </template>
            </el-table-column>
            <el-table-column prop="appDesc" label="描述"></el-table-column>
            <el-table-column prop="sortOrder" label="排序" width="80"></el-table-column>
            <el-table-column label="操作" width="260" align="center">
              <template slot-scope="scope">
                <el-button type="text" @click="openAppDialog(scope.row)">编辑</el-button>
                <el-button type="text" @click="toggleAppStatus(scope.row)">
                  {{ scope.row.appStatus === 'ENABLED' ? '禁用' : '启用' }}
                </el-button>
                <el-button type="text" class="danger-btn" @click="deleteApp(scope.row)">删除</el-button>
              </template>
            </el-table-column>
          </el-table>
        </el-tab-pane>
      </el-tabs>
    </div>

    <el-drawer :title="channelForm.id ? '编辑支付渠道' : '新增支付渠道'" :visible.sync="channelDialogVisible" size="560px" direction="rtl">
      <el-form ref="channelForm" :model="channelForm" :rules="channelRules" label-position="top" style="padding:0 8px">
        <el-form-item label="渠道名称" prop="channelName">
          <el-input v-model="channelForm.channelName"></el-input>
        </el-form-item>
        <el-form-item label="渠道编码" prop="channelCode">
          <el-input v-model="channelForm.channelCode" placeholder="例如：WXPAY、ALIPAY"></el-input>
        </el-form-item>
        <el-form-item label="状态" prop="channelStatus">
          <el-select v-model="channelForm.channelStatus" style="width: 100%">
            <el-option label="启用" value="ENABLED"></el-option>
            <el-option label="禁用" value="DISABLED"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="排序">
          <el-input-number v-model="channelForm.sortOrder" :min="0" :step="1"></el-input-number>
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="channelForm.channelDesc"></el-input>
        </el-form-item>
        <el-divider content-position="left">微信商户信息</el-divider>
        <el-form-item label="微信 AppID">
          <el-input v-model="channelForm.appid" placeholder="例如：wx74862e0dfcf69954"></el-input>
        </el-form-item>
        <el-form-item label="微信商户号">
          <el-input v-model="channelForm.mchId" placeholder="例如：1558950191"></el-input>
        </el-form-item>
        <el-form-item label="商户 API 证书序列号">
          <el-input v-model="channelForm.mchSerialNo"></el-input>
        </el-form-item>
        <el-form-item label="商户私钥（apiclient_key.pem 内容）">
          <el-input
            v-model="channelForm.privateKey"
            type="textarea"
            :rows="6"
            placeholder="-----BEGIN PRIVATE KEY----- ... -----END PRIVATE KEY-----"></el-input>
        </el-form-item>
        <el-form-item label="APIv3 密钥">
          <el-input v-model="channelForm.apiV3Key"></el-input>
        </el-form-item>
        <el-form-item label="APIv2 密钥（partnerKey）">
          <el-input v-model="channelForm.partnerKey"></el-input>
        </el-form-item>
        <el-divider content-position="left">支付宝商户信息</el-divider>
        <el-form-item label="支付宝应用 ID">
          <el-input v-model="channelForm.alipayAppId" placeholder="例如：9021000136667568"></el-input>
        </el-form-item>
        <el-form-item label="卖家 PID（seller_id）">
          <el-input v-model="channelForm.sellerId"></el-input>
        </el-form-item>
        <el-form-item label="应用私钥（base64）">
          <el-input v-model="channelForm.merchantPrivateKey" type="textarea" :rows="4"></el-input>
        </el-form-item>
        <el-form-item label="支付宝公钥（base64）">
          <el-input v-model="channelForm.alipayPublicKey" type="textarea" :rows="4"></el-input>
        </el-form-item>
        <el-form-item label="渠道参数JSON">
          <el-input
            v-model="channelForm.configParams"
            type="textarea"
            :rows="8"
            placeholder='例如：{"domain":"https://api.mch.weixin.qq.com"}'></el-input>
        </el-form-item>
      </el-form>
      <div slot="footer" style="text-align:right">
        <el-button @click="channelDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitChannel">保存</el-button>
      </div>
    </el-drawer>

    <el-drawer :title="appForm.id ? '编辑支付应用' : '新增支付应用'" :visible.sync="appDialogVisible" size="640px" direction="rtl">
      <el-form ref="appForm" :model="appForm" :rules="appRules" label-position="top" style="padding:0 8px">
        <el-form-item label="应用名称" prop="appName">
          <el-input v-model="appForm.appName"></el-input>
        </el-form-item>
        <el-form-item label="应用编码" prop="appCode">
          <el-input v-model="appForm.appCode" placeholder="例如：WXPAY_DEFAULT"></el-input>
        </el-form-item>
        <el-form-item label="所属渠道" prop="channelId">
          <el-select v-model="appForm.channelId" style="width: 100%" placeholder="请选择支付渠道">
            <el-option
              v-for="channel in channelList"
              :key="channel.id"
              :label="channel.channelName + '（' + channel.channelCode + '）'"
              :value="channel.id">
            </el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="状态" prop="appStatus">
          <el-select v-model="appForm.appStatus" style="width: 100%">
            <el-option label="启用" value="ENABLED"></el-option>
            <el-option label="禁用" value="DISABLED"></el-option>
          </el-select>
        </el-form-item>
        <el-form-item label="排序">
          <el-input-number v-model="appForm.sortOrder" :min="0" :step="1"></el-input-number>
        </el-form-item>
        <el-form-item label="描述">
          <el-input v-model="appForm.appDesc"></el-input>
        </el-form-item>
        <el-alert
          type="info"
          :closable="false"
          show-icon
          title="商户参数（appid/商户号/密钥等）统一在「支付渠道配置」中维护"
          style="margin-bottom:8px"></el-alert>
      </el-form>
      <div slot="footer" style="text-align:right">
        <el-button @click="appDialogVisible = false">取消</el-button>
        <el-button type="primary" @click="submitApp">保存</el-button>
      </div>
    </el-drawer>
  </div>
</template>

<script>
import paymentConfigApi from '../api/paymentConfig'

const defaultChannelForm = () => ({
  id: null,
  channelName: '',
  channelCode: '',
  channelStatus: 'ENABLED',
  channelDesc: '',
  configParams: '',
  appid: '',
  mchId: '',
  mchSerialNo: '',
  privateKey: '',
  apiV3Key: '',
  partnerKey: '',
  alipayAppId: '',
  sellerId: '',
  merchantPrivateKey: '',
  alipayPublicKey: '',
  sortOrder: 0
})

const defaultAppForm = () => ({
  id: null,
  appName: '',
  appCode: '',
  appStatus: 'ENABLED',
  channelId: null,
  appDesc: '',
  sortOrder: 0
})

export default {
  data() {
    return {
      activeTab: 'channel',
      channelList: [],
      appList: [],
      channelDialogVisible: false,
      appDialogVisible: false,
      channelForm: defaultChannelForm(),
      appForm: defaultAppForm(),
      channelRules: {
        channelName: [{ required: true, message: '请输入渠道名称', trigger: 'blur' }],
        channelCode: [{ required: true, message: '请输入渠道编码', trigger: 'blur' }],
        channelStatus: [{ required: true, message: '请选择状态', trigger: 'change' }]
      },
      appRules: {
        appName: [{ required: true, message: '请输入应用名称', trigger: 'blur' }],
        appCode: [{ required: true, message: '请输入应用编码', trigger: 'blur' }],
        channelId: [{ required: true, message: '请选择支付渠道', trigger: 'change' }],
        appStatus: [{ required: true, message: '请选择状态', trigger: 'change' }]
      }
    }
  },

  created() {
    this.loadChannels()
    this.loadApps()
  },

  methods: {
    loadChannels() {
      paymentConfigApi.listAllChannels().then(response => {
        this.channelList = response.data || []
      })
    },

    loadApps() {
      paymentConfigApi.listAllApps().then(response => {
        this.appList = response.data || []
      })
    },

    openChannelDialog(row) {
      this.channelForm = row ? Object.assign(defaultChannelForm(), row) : defaultChannelForm()
      this.channelDialogVisible = true
      this.$nextTick(() => this.$refs.channelForm && this.$refs.channelForm.clearValidate())
    },

    submitChannel() {
      this.$refs.channelForm.validate(valid => {
        if (!valid || !this.validateJson(this.channelForm.configParams)) {
          return
        }
        const request = this.channelForm.id
          ? paymentConfigApi.updateChannel(this.channelForm.id, this.channelForm)
          : paymentConfigApi.createChannel(this.channelForm)
        request.then(response => {
          this.$message.success(response.message || '保存成功')
          this.channelDialogVisible = false
          this.loadChannels()
          this.loadApps()
        })
      })
    },

    toggleChannelStatus(row) {
      const targetStatus = row.channelStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED'
      paymentConfigApi.updateChannelStatus(row.id, targetStatus).then(response => {
        this.$message.success(response.message || '状态修改成功')
        this.loadChannels()
        this.loadApps()
      })
    },

    deleteChannel(row) {
      this.$confirm('确认删除该支付渠道？若已有应用关联，数据库会拒绝删除。', '提示', { type: 'warning' })
        .then(() => paymentConfigApi.deleteChannel(row.id))
        .then(response => {
          this.$message.success(response.message || '删除成功')
          this.loadChannels()
          this.loadApps()
        })
        .catch(() => {})
    },

    openAppDialog(row) {
      this.appForm = row ? Object.assign(defaultAppForm(), row) : defaultAppForm()
      this.appDialogVisible = true
      this.$nextTick(() => this.$refs.appForm && this.$refs.appForm.clearValidate())
    },

    submitApp() {
      this.$refs.appForm.validate(valid => {
        if (!valid) {
          return
        }
        const request = this.appForm.id
          ? paymentConfigApi.updateApp(this.appForm.id, this.appForm)
          : paymentConfigApi.createApp(this.appForm)
        request.then(response => {
          this.$message.success(response.message || '保存成功')
          this.appDialogVisible = false
          this.loadApps()
        })
      })
    },

    toggleAppStatus(row) {
      const targetStatus = row.appStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED'
      paymentConfigApi.updateAppStatus(row.id, targetStatus).then(response => {
        this.$message.success(response.message || '状态修改成功')
        this.loadApps()
      })
    },

    deleteApp(row) {
      this.$confirm('确认删除该支付应用？历史订单仍会保留支付应用ID。', '提示', { type: 'warning' })
        .then(() => paymentConfigApi.deleteApp(row.id))
        .then(response => {
          this.$message.success(response.message || '删除成功')
          this.loadApps()
        })
        .catch(() => {})
    },

    reloadConfig() {
      paymentConfigApi.reload().then(response => {
        this.$message.success(response.message || '支付配置已重新加载')
      })
    },

    validateJson(value) {
      if (!value || !value.trim()) {
        return true
      }
      try {
        const parsed = JSON.parse(value)
        if (Object.prototype.toString.call(parsed) !== '[object Object]') {
          this.$message.error('配置参数必须是 JSON 对象')
          return false
        }
        return true
      } catch (e) {
        this.$message.error('JSON 格式不正确：' + e.message)
        return false
      }
    }
  }
}
</script>

<style scoped>
.toolbar {
  margin-bottom: 16px;
}
.danger-btn {
  color: #f56c6c;
}
</style>

// admin-ui/src/pages/PaymentConfig.jsx
import { useCallback, useEffect, useState } from 'react'
import { Alert, Button, Card, Divider, Drawer, Form, Input, InputNumber, message, Modal, Select, Space, Tabs, Table, Tag, Typography } from 'antd'
import paymentConfigApi from '@/api/paymentConfig'

const defaultChannelForm = () => ({
  id: null,
  channelName: '',
  channelCode: '',
  channelStatus: 'ENABLED',
  channelDesc: '',
  configParams: '',
  sortOrder: 0
})

const defaultAppForm = () => ({
  id: null,
  appName: '',
  appCode: '',
  appStatus: 'ENABLED',
  channelId: null,
  appDesc: '',
  sortOrder: 0
})

export default function PaymentConfig() {
  const [activeTab, setActiveTab] = useState('channel')
  const [channelList, setChannelList] = useState([])
  const [appList, setAppList] = useState([])
  const [channelDialogVisible, setChannelDialogVisible] = useState(false)
  const [appDialogVisible, setAppDialogVisible] = useState(false)
  const [channelForm] = Form.useForm()
  const [appForm] = Form.useForm()
  const [editingChannel, setEditingChannel] = useState(null)
  const [editingApp, setEditingApp] = useState(null)

  const loadChannels = useCallback(() => {
    paymentConfigApi.listAllChannels().then((response) => {
      setChannelList(response?.data || [])
    })
  }, [])

  const loadApps = useCallback(() => {
    paymentConfigApi.listAllApps().then((response) => {
      setAppList(response?.data || [])
    })
  }, [])

  useEffect(() => {
    loadChannels()
    loadApps()
  }, [loadChannels, loadApps])

  const openChannelDialog = (row) => {
    setEditingChannel(row || null)
    if (row) {
      channelForm.setFieldsValue({ ...row })
    } else {
      channelForm.setFieldsValue(defaultChannelForm())
    }
    setChannelDialogVisible(true)
  }

  const submitChannel = () => {
    channelForm.validateFields().then((values) => {
      if (values.configParams) {
        try {
          JSON.parse(values.configParams)
        } catch {
          message.error('渠道参数JSON格式错误')
          return
        }
      }

      const request = editingChannel
        ? paymentConfigApi.updateChannel(editingChannel.id, values)
        : paymentConfigApi.createChannel(values)

      request.then((response) => {
        message.success(response.message || '保存成功')
        setChannelDialogVisible(false)
        loadChannels()
        loadApps()
      })
    })
  }

  const toggleChannelStatus = (row) => {
    const targetStatus = row.channelStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED'
    paymentConfigApi.updateChannelStatus(row.id, targetStatus).then((response) => {
      message.success(response.message || '状态修改成功')
      loadChannels()
      loadApps()
    })
  }

  const deleteChannel = (row) => {
    Modal.confirm({
      title: '确认删除该支付渠道？',
      content: '若已有应用关联，数据库会拒绝删除。',
      okText: '确认',
      cancelText: '取消',
      onOk: () => {
        paymentConfigApi.deleteChannel(row.id).then((response) => {
          message.success(response.message || '删除成功')
          loadChannels()
          loadApps()
        })
      }
    })
  }

  const openAppDialog = (row) => {
    setEditingApp(row || null)
    if (row) {
      appForm.setFieldsValue({ ...row })
    } else {
      appForm.setFieldsValue(defaultAppForm())
    }
    setAppDialogVisible(true)
  }

  const submitApp = () => {
    appForm.validateFields().then((values) => {
      const request = editingApp
        ? paymentConfigApi.updateApp(editingApp.id, values)
        : paymentConfigApi.createApp(values)

      request.then((response) => {
        message.success(response.message || '保存成功')
        setAppDialogVisible(false)
        loadApps()
      })
    })
  }

  const toggleAppStatus = (row) => {
    const targetStatus = row.appStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED'
    paymentConfigApi.updateAppStatus(row.id, targetStatus).then((response) => {
      message.success(response.message || '状态修改成功')
      loadApps()
    })
  }

  const deleteApp = (row) => {
    Modal.confirm({
      title: '确认删除该支付应用？',
      content: '历史订单仍会保留支付应用ID。',
      okText: '确认',
      cancelText: '取消',
      onOk: () => {
        paymentConfigApi.deleteApp(row.id).then((response) => {
          message.success(response.message || '删除成功')
          loadApps()
        })
      }
    })
  }

  const reloadConfig = () => {
    paymentConfigApi.reload().then((response) => {
      message.success(response.message || '配置重新加载成功')
    })
  }

  const channelColumns = [
    { title: '#', width: 50, render: (_, __, index) => index + 1 },
    { title: '渠道名称', dataIndex: 'channelName', width: 140 },
    { title: '渠道编码', dataIndex: 'channelCode', width: 120 },
    {
      title: '状态',
      dataIndex: 'channelStatus',
      width: 110,
      render: (status) => (
        <Tag color={status === 'ENABLED' ? 'success' : 'default'}>{status}</Tag>
      )
    },
    { title: '描述', dataIndex: 'channelDesc' },
    { title: '排序', dataIndex: 'sortOrder', width: 80 },
    {
      title: '操作',
      width: 260,
      align: 'center',
      render: (_, row) => (
        <Space size="small">
          <Button type="link" onClick={() => openChannelDialog(row)}>编辑</Button>
          <Button type="link" onClick={() => toggleChannelStatus(row)}>
            {row.channelStatus === 'ENABLED' ? '禁用' : '启用'}
          </Button>
          <Button type="link" danger onClick={() => deleteChannel(row)}>删除</Button>
        </Space>
      )
    }
  ]

  const appColumns = [
    { title: '#', width: 50, render: (_, __, index) => index + 1 },
    { title: '应用名称', dataIndex: 'appName', width: 170 },
    { title: '应用编码', dataIndex: 'appCode', width: 190 },
    { title: '所属渠道', dataIndex: 'channelName', width: 120 },
    {
      title: '状态',
      dataIndex: 'appStatus',
      width: 110,
      render: (status) => (
        <Tag color={status === 'ENABLED' ? 'success' : 'default'}>{status}</Tag>
      )
    },
    { title: '描述', dataIndex: 'appDesc' },
    { title: '排序', dataIndex: 'sortOrder', width: 80 },
    {
      title: '操作',
      width: 260,
      align: 'center',
      render: (_, row) => (
        <Space size="small">
          <Button type="link" onClick={() => openAppDialog(row)}>编辑</Button>
          <Button type="link" onClick={() => toggleAppStatus(row)}>
            {row.appStatus === 'ENABLED' ? '禁用' : '启用'}
          </Button>
          <Button type="link" danger onClick={() => deleteApp(row)}>删除</Button>
        </Space>
      )
    }
  ]

  return (
    <div>
      <Typography.Title level={4} style={{ marginTop: 0, marginBottom: 16 }}>支付配置</Typography.Title>

      <Card>
        <Tabs
          activeKey={activeTab}
          onChange={setActiveTab}
          type="card"
          items={[
            {
              key: 'channel',
              label: '支付渠道配置',
              children: (
                <>
                  <Space style={{ marginBottom: 16 }}>
                    <Button type="primary" onClick={() => openChannelDialog()}>新增渠道</Button>
                    <Button onClick={loadChannels}>刷新</Button>
                    <Button type="primary" onClick={reloadConfig}>重新加载配置缓存</Button>
                  </Space>
                  <Table
                    rowKey="id"
                    dataSource={channelList}
                    columns={channelColumns}
                    bordered
                    pagination={false}
                  />
                </>
              )
            },
            {
              key: 'app',
              label: '支付应用配置',
              children: (
                <>
                  <Space style={{ marginBottom: 16 }}>
                    <Button type="primary" onClick={() => openAppDialog()}>新增应用</Button>
                    <Button onClick={loadApps}>刷新</Button>
                    <Button type="primary" onClick={reloadConfig}>重新加载配置缓存</Button>
                  </Space>
                  <Table
                    rowKey="id"
                    dataSource={appList}
                    columns={appColumns}
                    bordered
                    pagination={false}
                  />
                </>
              )
            }
          ]}
        />
      </Card>

      <Drawer
        title={editingChannel ? '编辑支付渠道' : '新增支付渠道'}
        open={channelDialogVisible}
        width={560}
        onClose={() => setChannelDialogVisible(false)}
        footer={<div style={{ textAlign: 'right' }}>
          <Button style={{ marginRight: 8 }} onClick={() => setChannelDialogVisible(false)}>取消</Button>
          <Button type="primary" onClick={submitChannel}>保存</Button>
        </div>}
      >
        <Form form={channelForm} layout="vertical">
          <Form.Item label="渠道名称" name="channelName" rules={[{ required: true, message: '请输入渠道名称' }]}>
            <Input />
          </Form.Item>
          <Form.Item label="渠道编码" name="channelCode" rules={[{ required: true, message: '请输入渠道编码' }]}>
            <Input placeholder="例如：WXPAY、ALIPAY" />
          </Form.Item>
          <Form.Item label="状态" name="channelStatus" rules={[{ required: true, message: '请选择状态' }]}>
            <Select>
              <Select.Option value="ENABLED">启用</Select.Option>
              <Select.Option value="DISABLED">禁用</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item label="排序" name="sortOrder" initialValue={0}>
            <InputNumber min={0} step={1} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item label="描述" name="channelDesc">
            <Input />
          </Form.Item>
          <Divider plain orientation="left">微信商户信息</Divider>
          <Form.Item label="微信 AppID" name="appid">
            <Input placeholder="例如：wx74862e0dfcf69954" />
          </Form.Item>
          <Form.Item label="微信商户号" name="mchId">
            <Input placeholder="例如：1558950191" />
          </Form.Item>
          <Form.Item label="商户 API 证书序列号" name="mchSerialNo">
            <Input />
          </Form.Item>
          <Form.Item label="商户私钥（apiclient_key.pem 内容）" name="privateKey">
            <Input.TextArea rows={6} placeholder={'-----BEGIN PRIVATE KEY-----\n...\n-----END PRIVATE KEY-----'} />
          </Form.Item>
          <Form.Item label="APIv3 密钥" name="apiV3Key">
            <Input />
          </Form.Item>
          <Form.Item label="APIv2 密钥（partnerKey）" name="partnerKey">
            <Input />
          </Form.Item>
          <Divider plain orientation="left">支付宝商户信息</Divider>
          <Form.Item label="支付宝应用 ID" name="alipayAppId">
            <Input placeholder="例如：9021000136667568" />
          </Form.Item>
          <Form.Item label="卖家 PID（seller_id）" name="sellerId">
            <Input />
          </Form.Item>
          <Form.Item label="应用私钥（base64）" name="merchantPrivateKey">
            <Input.TextArea rows={4} />
          </Form.Item>
          <Form.Item label="支付宝公钥（base64）" name="alipayPublicKey">
            <Input.TextArea rows={4} />
          </Form.Item>
          <Form.Item label="渠道参数JSON" name="configParams">
            <Input.TextArea rows={8} placeholder='例如：{"domain":"https://api.mch.weixin.qq.com"}' />
          </Form.Item>
        </Form>
      </Drawer>

      <Drawer
        title={editingApp ? '编辑支付应用' : '新增支付应用'}
        open={appDialogVisible}
        width={640}
        onClose={() => setAppDialogVisible(false)}
        footer={<div style={{ textAlign: 'right' }}>
          <Button style={{ marginRight: 8 }} onClick={() => setAppDialogVisible(false)}>取消</Button>
          <Button type="primary" onClick={submitApp}>保存</Button>
        </div>}
      >
        <Form form={appForm} layout="vertical">
          <Form.Item label="应用名称" name="appName" rules={[{ required: true, message: '请输入应用名称' }]}>
            <Input />
          </Form.Item>
          <Form.Item label="应用编码" name="appCode" rules={[{ required: true, message: '请输入应用编码' }]}>
            <Input placeholder="例如：WXPAY_DEFAULT" />
          </Form.Item>
          <Form.Item label="所属渠道" name="channelId" rules={[{ required: true, message: '请选择支付渠道' }]}>
            <Select placeholder="请选择支付渠道">
              {channelList.map((channel) => (
                <Select.Option key={channel.id} value={channel.id}>
                  {channel.channelName}（{channel.channelCode}）
                </Select.Option>
              ))}
            </Select>
          </Form.Item>
          <Form.Item label="状态" name="appStatus" rules={[{ required: true, message: '请选择状态' }]}>
            <Select>
              <Select.Option value="ENABLED">启用</Select.Option>
              <Select.Option value="DISABLED">禁用</Select.Option>
            </Select>
          </Form.Item>
          <Form.Item label="排序" name="sortOrder" initialValue={0}>
            <InputNumber min={0} step={1} style={{ width: '100%' }} />
          </Form.Item>
          <Form.Item label="描述" name="appDesc">
            <Input />
          </Form.Item>
          <Alert
            type="info"
            showIcon
            message="商户参数（appid/商户号/密钥等）统一在「支付渠道配置」中维护"
            style={{ marginBottom: 8 }}
          />
        </Form>
      </Drawer>
    </div>
  )
}
