// user-ui/src/pages/Cart.jsx
import { useEffect, useMemo, useState } from 'react'
import { Button, Cascader, Empty, Form, Input, Modal, message } from 'antd'
import { Link } from 'react-router-dom'
import cartApi from '@/api/cart'
import checkoutApi from '@/api/checkout'
import paymentConfigApi from '@/api/paymentConfig'
import addressApi from '@/api/address'
import request from '@/utils/request'
import { mallImg, onMallImgError } from '@/assets/mallImgs'

const paymentTypeOf = code => code === 'WXPAY' ? '微信' : code === 'ALIPAY' ? '支付宝' : ''
const CHANNEL_META = {
  WXPAY: { name: '微信支付', desc: '使用微信扫码支付（沙箱演示）', glyph: '微', cls: 'wx' },
  ALIPAY: { name: '支付宝', desc: '跳转支付宝完成支付（沙箱演示）', glyph: '支', cls: 'ali' }
}
const channelMetaOf = code => CHANNEL_META[code] || { name: code, desc: '沙箱演示渠道', glyph: (code || '?').slice(0, 1), cls: '' }

export default function Cart() {
  const [items, setItems] = useState([])
  const [apps, setApps] = useState([])
  const [channelCode, setChannelCode] = useState('')
  const [addressList, setAddressList] = useState([])
  const [selectedAddrId, setSelectedAddrId] = useState(null)
  const [addrOpen, setAddrOpen] = useState(false)
  const [addrForm] = Form.useForm()
  const [regions, setRegions] = useState([])
  const load = async () => {
    const [cart, payApps, addrs] = await Promise.all([cartApi.list(), paymentConfigApi.listEnabledApps(), addressApi.list()])
    setItems(cart.data || [])
    setApps(payApps.data || [])
    const list = addrs.data || []
    setAddressList(list)
    if (list.length > 0) {
      const def = list.find(a => a.isDefault === '1') || list[0]
      setSelectedAddrId(def.id)
    } else {
      setSelectedAddrId(null)
    }
  }
  useEffect(() => { load() }, []) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(() => { request.get('/api/regions/tree').then(r => setRegions(r.data || [])).catch(() => {}) }, [])

  const channels = useMemo(() => {
    const seen = new Set(); const list = []
    for (const a of apps) {
      if (!a.channelCode || seen.has(a.channelCode)) continue
      seen.add(a.channelCode)
      list.push({ code: a.channelCode, appId: a.id, ...channelMetaOf(a.channelCode) })
    }
    return list
  }, [apps])
  useEffect(() => {
    if (!channels.some(c => c.code === channelCode)) setChannelCode(channels[0]?.code || '')
  }, [channels]) // eslint-disable-line react-hooks/exhaustive-deps

  const selectedItems = items.filter(i => i.selected)
  const total = selectedItems.reduce((s, i) => s + Number(i.latestPrice || 0) * Number(i.quantity || 0), 0)
  const canCheckout = selectedItems.length > 0 && selectedItems.every(i => i.available) && Boolean(channelCode)
  const changeQty = async (row, q) => { await cartApi.put({ productId: row.productId, quantity: q, selected: row.selected }); await load() }

  const checkout = async () => {
    const app = apps.find(a => a.channelCode === channelCode)
    if (!app) return message.error('请选择支付方式')
    const paymentType = paymentTypeOf(channelCode)
    if (!paymentType) return message.error(`暂不支持渠道 ${channelCode}`)
    const payload = { paymentType, paymentAppId: app.id }
    if (selectedAddrId) payload.addressId = selectedAddrId
    const r = await checkoutApi.create(payload)
    message.success(`订单已创建：${r.data?.order?.orderNo}`)
    location.hash = '#/orders'
  }

  const submitAddr = async () => {
    const v = await addrForm.validateFields()
    const [province, city, district] = v.region || []
    const payload = {
      receiverName: v.receiverName, receiverPhone: v.receiverPhone, detail: v.detail,
      province: regions.find(p => p.value === province)?.label || province || '',
      city: regions.find(p => p.value === province)?.children?.find(c => c.value === city)?.label || city || '',
      district: regions.find(p => p.value === province)?.children?.find(c => c.value === city)?.children?.find(d => d.value === district)?.label || district || '',
      isDefault: v.isDefault ? '1' : '0'
    }
    const r = await addressApi.create(payload)
    message.success('已新增'); setAddrOpen(false); setAddrSelected(r.data.id); await load()
  }
  const setAddrSelected = (id) => setSelectedAddrId(id)

  return <div className="tb-page">
    <div className="container">
      <h2 className="tb-h2">我的购物车</h2>
      {items.length === 0
        ? <div className="tb-cardbox"><Empty description="购物车还是空的">
          <Link to="/"><Button type="primary">去逛逛</Button></Link>
        </Empty></div>
        : items.map(r => (
        <div className="tb-cart-card" key={r.productId}>
          <label className="tb-cart-check">
            <input type="checkbox" checked={r.selected} onChange={async e => { await cartApi.select(r.productId, e.target.checked); await load() }} />
          </label>
          <div className="tb-cart-thumb" style={{ aspectRatio: '1/1' }}>
            <img src={mallImg(r.productId)} alt={r.title} onError={onMallImgError} />
          </div>
          <div className="tb-cart-info">
            <div className="tb-goods-title">{r.title}</div>
            <div className="tb-cart-sub">{r.available ? `可售 · 库存 ${r.availableStock}` : '库存不足'}</div>
            <div className="tb-cart-meta">
              <span className="tb-cart-price">¥{((r.latestPrice || 0) / 100).toFixed(2)}</span>
              <span className="tb-cart-del" onClick={async () => { await cartApi.remove(r.productId); await load() }}>删除</span>
              <div className="tb-cart-qty">
                <button type="button" disabled={r.quantity <= 1} onClick={() => changeQty(r, r.quantity - 1)}>-</button>
                <span>{r.quantity}</span>
                <button type="button" disabled={!r.available || r.quantity >= (r.availableStock || 99)} onClick={() => changeQty(r, r.quantity + 1)}>+</button>
              </div>
            </div>
          </div>
        </div>
      ))}
      {items.length > 0 && <div className="tb-receiver">
        <div className="tb-addr-row">
          <div className="tb-addr-label">收货地址</div>
          {addressList.length === 0 ? (
            <div className="tb-addr-empty">暂无地址
              <Button size="small" type="link" onClick={() => { addrForm.resetFields(); addrForm.setFieldsValue({ isDefault: true }); setAddrOpen(true) }}>+ 立即新增</Button>
              <Link to="/addresses" className="tb-addr-link" style={{ fontSize: 12, marginLeft: 8 }}>地址管理</Link>
            </div>
          ) : (
            <div className="tb-addr-list">
              {addressList.map(a => (
                <div key={a.id} className={`tb-addr-item${selectedAddrId === a.id ? ' active' : ''}`} onClick={() => setAddrSelected(a.id)}>
                  <div className="tb-addr-head">
                    <b>{a.receiverName}</b> <span>{a.receiverPhone}</span>
                    {a.isDefault === '1' && <span className="tb-addr-tag">默认</span>}
                  </div>
                  <div className="tb-addr-body">{a.province}{a.city}{a.district}{a.detail}</div>
                </div>
              ))}
              <Button size="small" type="dashed" style={{ height: 56, width: 110 }} onClick={() => { addrForm.resetFields(); addrForm.setFieldsValue({ isDefault: addressList.length === 0 }); setAddrOpen(true) }}>+ 新增</Button>
              <Link to="/addresses" className="tb-addr-link">管理 ›</Link>
            </div>
          )}
        </div>
        <div className="m-pay-label">支付方式</div>
        <div className="m-pay-list">
          {channels.map(c => (
            <div key={c.code} className={`m-pay-item${c.code === channelCode ? ' active' : ''}`} onClick={() => setChannelCode(c.code)}>
              <div className={`m-pay-logo ${c.cls}`}>{c.glyph}</div>
              <div className="m-pay-info">
                <div className="m-pay-name">{c.name}</div>
                <div className="m-pay-desc">{c.desc}</div>
              </div>
              <div className="m-pay-check" />
            </div>
          ))}
        </div>
      </div>}
      <div className="tb-cart-bar">
        <span className="m-dim">已选 <b className="m-count">{selectedItems.length}</b> 件商品</span>
        <div className="tb-cart-total">合计：<b>¥{(total / 100).toFixed(2)}</b></div>
        <Button className="tb-cart-checkout" disabled={!canCheckout} onClick={checkout}>结 算</Button>
      </div>
    </div>
    <Modal open={addrOpen} onCancel={() => setAddrOpen(false)} title="新增收货地址" onOk={submitAddr}>
      <Form form={addrForm} layout="vertical" preserve={false}>
        <Form.Item name="receiverName" label="收货人" rules={[{ required: true, message: '请输入收货人姓名' }]}><Input maxLength={32} /></Form.Item>
        <Form.Item name="receiverPhone" label="电话" rules={[{ required: true, message: '请输入手机号' }, { pattern: /^1[3-9]\d{9}$/, message: '手机号格式不正确' }]}><Input maxLength={32} /></Form.Item>
        <Form.Item name="region" label="所在地区" rules={[{ required: true, message: '请选择省/市/区' }]}><Cascader options={regions} placeholder="省 / 市 / 区" changeOnSelect /></Form.Item>
        <Form.Item name="detail" label="详细地址" rules={[{ required: true, message: '请输入详细地址' }]}><Input.TextArea maxLength={128} rows={2} placeholder="街道、门牌号等" /></Form.Item>
      </Form>
    </Modal>
  </div>
}

// payment-demo-vue/src/views/Cart.vue
<template>
  <div class="tb-page">
    <div class="container">
      <h2 class="tb-h2">我的购物车</h2>
      <div class="tb-cart-head">
        <div class="tb-col-check">勾选</div>
        <div class="tb-col-goods">商品信息</div>
        <div class="tb-col-price">单价</div>
        <div class="tb-col-qty">数量</div>
        <div class="tb-col-sum">小计</div>
        <div class="tb-col-op">操作</div>
      </div>
      <div v-if="items.length === 0" class="tb-cardbox">
        <a-empty description="购物车还是空的，去挑点好物吧"/>
      </div>
      <div class="tb-cart-row" v-for="r in items" :key="r.productId">
        <div class="tb-col-check"><el-checkbox :value="!!r.selected" @change="select(r, $event)"/></div>
        <div class="tb-col-goods">
          <img :src="mallImg(r.productId)" :alt="r.title" @error="onMallImgError"/>
          <div style="min-width:0">
            <div class="tb-goods-title">{{r.title}}</div>
            <div class="tb-goods-sub">{{r.available ? '可售 · 可用库存 ' + r.availableStock : '不可售 / 库存不足'}}</div>
          </div>
        </div>
        <div class="tb-col-price">¥{{money(r.latestPrice)}}</div>
        <div class="tb-col-qty"><el-input-number :value="r.quantity" :min="1" :max="Math.max(1,Number(r.availableStock||1))" size="small" @change="changeQty(r, $event)"/></div>
        <div class="tb-col-sum">¥{{money(Number(r.latestPrice||0) * Number(r.quantity||0))}}</div>
        <div class="tb-col-op"><a @click="remove(r)">删除</a></div>
      </div>
      <div v-if="items.length > 0" class="tb-receiver">
        <el-input v-model.trim="receiver.name" placeholder="收货人姓名（选填）" style="width:140px"/>
        <el-input v-model.trim="receiver.phone" placeholder="收货人电话（选填）" style="width:160px"/>
        <el-input v-model.trim="receiver.address" placeholder="收货地址（选填，缺省模拟值）" style="width:320px"/>
        <div class="m-pay-label">支付方式</div>
        <div class="m-pay-list">
          <div v-for="c in channels" :key="c.code" class="m-pay-item" :class="{active: c.code === channelCode}" @click="channelCode = c.code">
            <div class="m-pay-logo" :class="c.cls">{{c.glyph}}</div>
            <div class="m-pay-info">
              <div class="m-pay-name">{{c.name}}</div>
              <div class="m-pay-desc">{{c.desc}}</div>
            </div>
            <div class="m-pay-check"></div>
          </div>
        </div>
      </div>
      <div v-if="items.length > 0" class="tb-cart-bar">
        <span class="m-dim">已选 <b class="m-count">{{selectedItems.length}}</b> 件商品</span>
        <div class="tb-cart-total">合计：<b>¥{{money(total)}}</b></div>
        <button class="tb-cart-checkout" :disabled="!canCheckout" @click="checkout">结 算</button>
      </div>
    </div>
  </div>
</template>
<script>
import cartApi from '../api/cart'
import checkoutApi from '../api/checkout'
import paymentConfigApi from '../api/paymentConfig'
import { mallImg, onMallImgError } from '../assets/mallImgs'

var CHANNEL_META = {
  WXPAY: { name: '微信支付', desc: '使用微信扫码支付（沙箱演示）', glyph: '微', cls: 'wx' },
  ALIPAY: { name: '支付宝', desc: '跳转支付宝完成支付（沙箱演示）', glyph: '支', cls: 'ali' }
}
function channelMetaOf(code) {
  return CHANNEL_META[code] || { name: code, desc: '沙箱演示渠道', glyph: String(code || '?').slice(0, 1), cls: '' }
}

export default {
  data() { return { items: [], apps: [], channelCode: '', receiver: { name: '', phone: '', address: '' } } },
  computed: {
    // 渠道级去重：同渠道多应用时默认取第一个启用应用，用户视角只感知「支付方式」
    channels() {
      var seen = {}
      var list = []
      this.apps.forEach(a => {
        if (!a.channelCode || seen[a.channelCode]) return
        seen[a.channelCode] = true
        var meta = channelMetaOf(a.channelCode)
        list.push({ code: a.channelCode, appId: a.id, name: meta.name, desc: meta.desc, glyph: meta.glyph, cls: meta.cls })
      })
      return list
    },
    selectedItems() { return this.items.filter(i => i.selected) },
    total() { return this.selectedItems.reduce((s, i) => s + Number(i.latestPrice || 0) * Number(i.quantity || 0), 0) },
    canCheckout() { return this.selectedItems.length > 0 && this.selectedItems.every(i => i.available) && !!this.channelCode }
  },
  created() { this.load() },
  methods: {
    mallImg,
    onMallImgError,
    money(v) { return (Number(v || 0) / 100).toFixed(2) },
    async load() {
      const rs = await Promise.all([cartApi.list(), paymentConfigApi.listEnabledApps()])
      this.items = rs[0].data || []
      this.apps = rs[1].data || []
      if (!this.channels.some(c => c.code === this.channelCode)) {
        this.channelCode = this.channels.length ? this.channels[0].code : ''
      }
    },
    async select(row, v) { await cartApi.select(row.productId, v); await this.load() },
    async changeQty(row, v) { await cartApi.put({ productId: row.productId, quantity: Number(v || 1), selected: !!row.selected }); await this.load() },
    async remove(row) { await cartApi.remove(row.productId); await this.load() },
    async checkout() {
      const app = this.apps.find(a => a.channelCode === this.channelCode)
      if (!app) return this.$message.error('请选择支付方式')
      const paymentType = this.channelCode === 'WXPAY' ? '微信' : this.channelCode === 'ALIPAY' ? '支付宝' : ''
      if (!paymentType) return this.$message.error('暂不支持渠道：' + this.channelCode)
      const r = await checkoutApi.create({
        paymentType: paymentType, paymentAppId: app.id,
        receiverName: this.receiver.name || undefined,
        receiverPhone: this.receiver.phone || undefined,
        receiverAddress: this.receiver.address || undefined
      })
      this.$message.success('订单已创建：' + r.data.order.orderNo); this.$router.push('/orders')
    }
  }
}
</script>
