// admin-ui/src/pages/AdminProducts.jsx
import { useEffect, useState } from 'react'
import { Button, Card, Descriptions, Drawer, Input, InputNumber, message, Space, Spin, Table, Tag, Typography } from 'antd'
import stockApi from '@/api/adminStock'

export default function AdminProducts() {
  const [products, setProducts] = useState([])
  const [stockDelta, setStockDelta] = useState({})
  const [pcVisible, setPcVisible] = useState(false)
  const [pcForm, setPcForm] = useState({ title: '', price: 100, stock: 100 })
  const [detailId, setDetailId] = useState(null)
  const [detail, setDetail] = useState(null)
  const [detailLoading, setDetailLoading] = useState(false)
  const [drawerDelta, setDrawerDelta] = useState(null)

  const loadProducts = () => { stockApi.products().then(r => setProducts(r.data || [])) }
  useEffect(loadProducts, [])
  const loadDetail = async () => {
    if (!detailId) return
    setDetailLoading(true)
    try { const res = await stockApi.getProduct(detailId); setDetail(res.data) }
    catch (e) { message.error('加载失败') }
    finally { setDetailLoading(false) }
  }
  useEffect(() => { if (detailId) { setDetail(null); setDrawerDelta(null); loadDetail() } }, [detailId])

  const openDetail = p => setDetailId(p.id)
  const adjustStock = async (p, delta) => {
    if (!delta) { message.error('请输入库存调整量'); return }
    await stockApi.adjustStock(p.id, delta); message.success('库存已更新')
    setStockDelta(s => ({ ...s, [p.id]: undefined })); loadProducts()
  }
  const setStatus = async (p, productStatus) => { await stockApi.setStatus(p.id, productStatus); message.success('状态已更新'); loadProducts() }

  const p = detail?.product
  const drawerAdjust = async () => {
    if (!drawerDelta || drawerDelta === 0) return message.warning('请输入调整量')
    try { await stockApi.adjustStock(detailId, drawerDelta); message.success('库存已调整'); setDrawerDelta(null); await loadDetail(); loadProducts() }
    catch (e) { message.error(e.response?.data?.message || '调整失败') }
  }
  const drawerToggle = async () => {
    const ns = p.productStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED'
    try { await stockApi.setStatus(detailId, ns); message.success(ns === 'ENABLED' ? '已上架' : '已下架'); await loadDetail(); loadProducts() }
    catch (e) { message.error(e.response?.data?.message || '操作失败') }
  }

  const productCols = [
    { title: 'ID', dataIndex: 'id', width: 60 },
    { title: '商品', dataIndex: 'title', render: (text, p) => <a onClick={() => openDetail(p)}>{text}</a> },
    { title: '价格(分)', dataIndex: 'price', width: 90 },
    { title: '可用库存', dataIndex: 'stock', width: 90 },
    { title: '锁定库存', dataIndex: 'lockedStock', width: 90 },
    { title: '已售库存', dataIndex: 'soldStock', width: 90 },
    { title: '状态', dataIndex: 'productStatus', width: 90, render: v => <Tag color={v === 'ENABLED' ? 'green' : 'default'}>{v}</Tag> },
    { title: '库存调整', width: 220, render: (_, p) => <Space><InputNumber value={stockDelta[p.id]} placeholder="±数量" onChange={v2 => setStockDelta(s => ({ ...s, [p.id]: v2 }))} style={{ width: 110 }} /><Button type="primary" onClick={() => adjustStock(p, stockDelta[p.id])}>确认调整</Button></Space> },
    { title: '上下架', width: 150, render: (_, p) => <Button onClick={() => setStatus(p, p.productStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED')}>{p.productStatus === 'ENABLED' ? '下架' : '上架'}</Button> }
  ]
  const logCols = [
    { title: '时间', dataIndex: 'createTime', width: 165, render: v => v ? new Date(v).toLocaleString() : '-' },
    { title: '业务单号', dataIndex: 'bizNo', width: 210, ellipsis: true },
    { title: '类型', dataIndex: 'operationType', width: 130 },
    { title: '状态', dataIndex: 'operationStatus', width: 80, render: v => <Tag color={v === 'SUCCESS' ? 'green' : v === 'NEED_MANUAL' ? 'red' : 'orange'}>{v}</Tag> },
    { title: '调整量', dataIndex: 'availableDelta', width: 80, render: v => v == null ? '-' : <span style={{ color: v > 0 ? '#52c41a' : v < 0 ? '#f5222d' : '#8c8c8c' }}>{v > 0 ? `+${v}` : v}</span> },
    { title: '关联订单', dataIndex: 'orderNo', ellipsis: true }
  ]

  return <div>
    <Typography.Title level={4} style={{ marginTop: 0, marginBottom: 16 }}>商品库存</Typography.Title>
    <Card>
    <Button type="primary" style={{ marginBottom: 16 }} onClick={() => setPcVisible(true)}>新增商品</Button>
    <Table rowKey="id" dataSource={products} columns={productCols} />
    <Drawer open={detailId != null} width={720} onClose={() => setDetailId(null)} title={p ? `商品详情 - ${p.title}` : '商品详情'}>
      {detailLoading || !p ? <Spin style={{ display: 'block', margin: '80px auto' }} /> : <div>
        <Descriptions column={2} bordered style={{ marginBottom: 16 }}>
          <Descriptions.Item label="ID">{p.id}</Descriptions.Item>
          <Descriptions.Item label="商品名称">{p.title}</Descriptions.Item>
          <Descriptions.Item label="价格">¥{((p.price || 0) / 100).toFixed(2)}（{p.price}分）</Descriptions.Item>
          <Descriptions.Item label="状态"><Tag color={p.productStatus === 'ENABLED' ? 'green' : 'default'}>{p.productStatus}</Tag></Descriptions.Item>
          <Descriptions.Item label="可用库存">{p.stock}</Descriptions.Item>
          <Descriptions.Item label="锁定库存">{p.lockedStock}</Descriptions.Item>
          <Descriptions.Item label="已售库存">{p.soldStock}</Descriptions.Item>
          <Descriptions.Item label="创建时间">{p.createTime ? new Date(p.createTime).toLocaleString() : '-'}</Descriptions.Item>
          <Descriptions.Item label="更新时间">{p.updateTime ? new Date(p.updateTime).toLocaleString() : '-'}</Descriptions.Item>
        </Descriptions>
        <Space style={{ marginBottom: 16 }}>
          <span>调整量（正数补货，负数扣减）：</span>
          <InputNumber value={drawerDelta} onChange={v => setDrawerDelta(v)} placeholder="±数量" style={{ width: 150 }} />
          <Button type="primary" onClick={drawerAdjust}>确认调整</Button>
          <Button danger={p.productStatus === 'ENABLED'} onClick={drawerToggle}>{p.productStatus === 'ENABLED' ? '下架' : '上架'}</Button>
        </Space>
        <h4>库存操作日志（最近20条）</h4>
        <Table rowKey="id" dataSource={detail.logs || []} columns={logCols} pagination={false} size="small" />
      </div>}
    </Drawer>
    <Drawer open={pcVisible} width={480} onClose={() => setPcVisible(false)} title="新增商品"
      footer={<div style={{ textAlign: 'right' }}>
        <Button style={{ marginRight: 8 }} onClick={() => setPcVisible(false)}>取消</Button>
        <Button type="primary" onClick={async () => {
          if (!pcForm.title || !pcForm.price || pcForm.price <= 0) { message.error('请填写商品名称和有效价格'); return }
          await stockApi.createProduct({ title: pcForm.title.trim(), price: pcForm.price, stock: pcForm.stock || 0 })
          message.success('商品已创建'); setPcVisible(false); setPcForm({ title: '', price: 100, stock: 100 }); loadProducts()
        }}>创建</Button>
      </div>}>
      <Space direction="vertical" style={{ width: '100%' }} size={16}>
        <div><label style={{ display: 'block', marginBottom: 6 }}>商品名称</label><Input placeholder="请输入商品名称" value={pcForm.title} onChange={e => setPcForm({ ...pcForm, title: e.target.value })} /></div>
        <div><label style={{ display: 'block', marginBottom: 6 }}>价格（分）</label><InputNumber min={1} style={{ width: '100%' }} placeholder="如 1000 表示 ¥10.00" value={pcForm.price} onChange={v => setPcForm({ ...pcForm, price: v || 0 })} /></div>
        <div><label style={{ display: 'block', marginBottom: 6 }}>初始库存</label><InputNumber min={0} style={{ width: '100%' }} value={pcForm.stock} onChange={v => setPcForm({ ...pcForm, stock: v || 0 })} /></div>
      </Space>
    </Drawer>
    </Card>
  </div>
}

// payment-demo-vue-admin/src/views/AdminProducts.vue
<template>
  <div>
    <h2 class="adm-page-title">商品库存</h2>
    <div class="adm-card">
    <div style="margin-bottom:16px"><el-button type="primary" size="small" @click="pcVisible=true">新增商品</el-button></div>
    <el-table :data="products" style="width:100%">
      <el-table-column prop="id" label="ID" width="60"/>
      <el-table-column prop="title" label="商品" min-width="140"><template slot-scope="s"><a @click="openDetail(s.row)" style="cursor:pointer;color:#409eff">{{s.row.title}}</a></template></el-table-column>
      <el-table-column prop="price" label="价格(分)" width="90"/>
      <el-table-column prop="stock" label="可用库存" width="90"/>
      <el-table-column prop="lockedStock" label="锁定库存" width="90"/>
      <el-table-column prop="soldStock" label="已售库存" width="90"/>
      <el-table-column label="状态" width="100"><template slot-scope="s"><el-tag :type="s.row.productStatus==='ENABLED'?'success':'info'">{{s.row.productStatus}}</el-tag></template></el-table-column>
      <el-table-column label="库存调整" width="260"><template slot-scope="s"><el-input-number v-model="stockDelta[s.row.id]" size="small" style="width:130px" placeholder="±数量"/><el-button size="mini" type="primary" style="margin-left:8px" @click="adjustStock(s.row)">确认调整</el-button></template></el-table-column>
      <el-table-column label="上下架" width="100"><template slot-scope="s"><el-button size="mini" @click="setStatus(s.row)">{{s.row.productStatus==='ENABLED'?'下架':'上架'}}</el-button></template></el-table-column>
    </el-table>
    </div>
    <el-drawer :title="product.id ? '商品详情 - ' + product.title : '商品详情'" :visible.sync="detailVisible" size="720px" direction="rtl">
      <div v-loading="detailLoading" style="padding:0 8px">
        <el-descriptions :column="2" border style="margin-bottom:16px">
          <el-descriptions-item label="ID">{{product.id}}</el-descriptions-item>
          <el-descriptions-item label="商品名称">{{product.title}}</el-descriptions-item>
          <el-descriptions-item label="价格">¥{{((product.price||0)/100).toFixed(2)}}（{{product.price}}分）</el-descriptions-item>
          <el-descriptions-item label="状态"><el-tag :type="product.productStatus==='ENABLED'?'success':'info'" size="small">{{product.productStatus}}</el-tag></el-descriptions-item>
          <el-descriptions-item label="可用库存">{{product.stock}}</el-descriptions-item>
          <el-descriptions-item label="锁定库存">{{product.lockedStock}}</el-descriptions-item>
          <el-descriptions-item label="已售库存">{{product.soldStock}}</el-descriptions-item>
          <el-descriptions-item label="创建时间">{{product.createTime||'-'}}</el-descriptions-item>
          <el-descriptions-item label="更新时间">{{product.updateTime||'-'}}</el-descriptions-item>
        </el-descriptions>
        <div style="margin-bottom:16px">
          <span>调整量（正数补货，负数扣减）：</span>
          <el-input-number v-model="drawerDelta" :step="1" placeholder="±数量" style="width:150px;margin:0 8px"/>
          <el-button type="primary" size="small" @click="drawerAdjust">确认调整</el-button>
          <el-button size="small" :type="product.productStatus==='ENABLED'?'danger':'primary'" @click="drawerToggle">{{product.productStatus==='ENABLED'?'下架':'上架'}}</el-button>
        </div>
        <h4>库存操作日志（最近20条）</h4>
        <el-table :data="logs" size="small" style="width:100%">
          <el-table-column prop="createTime" label="时间" width="165"/>
          <el-table-column prop="bizNo" label="业务单号" width="210" show-overflow-tooltip/>
          <el-table-column prop="operationType" label="类型" width="130"/>
          <el-table-column label="状态" width="80"><template slot-scope="s"><el-tag :type="s.row.operationStatus==='SUCCESS'?'success':s.row.operationStatus==='NEED_MANUAL'?'danger':'warning'" size="mini">{{s.row.operationStatus}}</el-tag></template></el-table-column>
          <el-table-column label="调整量" width="80"><template slot-scope="s"><span :style="{color:(s.row.availableDelta||0)>0?'#67C23A':(s.row.availableDelta||0)<0?'#F56C6C':'#909399'}">{{s.row.availableDelta==null?'-':(s.row.availableDelta>0?'+':'')+s.row.availableDelta}}</span></template></el-table-column>
          <el-table-column prop="orderNo" label="关联订单" min-width="180" show-overflow-tooltip/>
        </el-table>
      </div>
    </el-drawer>
    <el-drawer title="新增商品" :visible.sync="pcVisible" size="480px" direction="rtl">
      <el-form label-position="top" style="padding:0 8px">
        <el-form-item label="商品名称">
          <el-input v-model.trim="pcForm.title" maxlength="100" placeholder="请输入商品名称"/>
        </el-form-item>
        <el-form-item label="价格（分）">
          <el-input-number v-model="pcForm.price" :min="1" style="width:100%" placeholder="如 1000 表示 ¥10.00"/>
        </el-form-item>
        <el-form-item label="初始库存">
          <el-input-number v-model="pcForm.stock" :min="0" style="width:100%"/>
        </el-form-item>
      </el-form>
      <div slot="footer" style="text-align:right">
        <el-button @click="pcVisible=false">取消</el-button>
        <el-button type="primary" @click="createProduct">创建</el-button>
      </div>
    </el-drawer>
  </div>
</template>
<script>
import stockApi from '../api/adminStock'
export default {
  data() { return { products: [], stockDelta: {}, pcVisible: false, pcForm: { title: '', price: 100, stock: 100 }, detailVisible: false, detailLoading: false, detailId: null, product: {}, logs: [], drawerDelta: null } },
  created() { this.load() },
  methods: {
    async load() { const r = await stockApi.products(); this.products = r.data || [] },
    async openDetail(row) {
      this.detailId = row.id; this.detailVisible = true; this.detailLoading = true; this.product = {}; this.logs = []; this.drawerDelta = null
      try {
        const res = await stockApi.getProduct(row.id)
        this.product = res.data.product || {}
        this.logs = res.data.logs || []
      } catch (e) { this.$message.error('加载失败') }
      finally { this.detailLoading = false }
    },
    async adjustStock(row) { const delta = this.stockDelta[row.id]; if (!delta) return this.$message.error('请输入库存调整量'); await stockApi.adjustStock(row.id, delta); this.$message.success('库存已更新'); this.stockDelta = { ...this.stockDelta, [row.id]: undefined }; await this.load() },
    async setStatus(row) { await stockApi.setStatus(row.id, row.productStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED'); this.$message.success('状态已更新'); await this.load() },
    async drawerAdjust() {
      if (!this.drawerDelta || this.drawerDelta === 0) return this.$message.warning('请输入调整量')
      try { await stockApi.adjustStock(this.detailId, this.drawerDelta); this.$message.success('库存已调整'); this.drawerDelta = null; await this.openDetail({ id: this.detailId }); await this.load() }
      catch (e) { this.$message.error('调整失败') }
    },
    async drawerToggle() {
      const ns = this.product.productStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED'
      try { await stockApi.setStatus(this.detailId, ns); this.$message.success(ns === 'ENABLED' ? '已上架' : '已下架'); await this.openDetail({ id: this.detailId }); await this.load() }
      catch (e) { this.$message.error('操作失败') }
    },
    async createProduct() {
      if (!this.pcForm.title || !this.pcForm.price || this.pcForm.price <= 0) return this.$message.error('请填写商品名称和有效价格')
      await stockApi.createProduct({ title: this.pcForm.title.trim(), price: this.pcForm.price, stock: this.pcForm.stock || 0 })
      this.$message.success('商品已创建'); this.pcVisible = false; this.pcForm = { title: '', price: 100, stock: 100 }; await this.load()
    }
  }
}
</script>
