// admin-ui/src/pages/AdminResetPassword.jsx
import { useEffect, useState } from 'react'
import { Button, Card, Input, Space, Table, Tag, message, Typography } from 'antd'
import authApi from '@/api/auth'

export default function AdminResetPassword() {
  const [records, setRecords] = useState([])
  const [total, setTotal] = useState(0)
  const [keyword, setKeyword] = useState('')
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)
  const [selected, setSelected] = useState(null)
  const [pwd, setPwd] = useState('')

  const load = async (p = page, kw = keyword) => {
    setLoading(true)
    try {
      const params = { page: p, size: 10 }
      if (kw.trim()) params.keyword = kw.trim()
      const r = await authApi.adminUsers(params)
      setRecords((r.data && r.data.records) || [])
      setTotal((r.data && r.data.total) || 0)
    } catch (e) { /* 拦截器已提示 */ }
    finally { setLoading(false) }
  }
  useEffect(() => { load(1, '') }, [])

  const search = () => { setPage(1); load(1, keyword) }
  const resetFilter = () => { setKeyword(''); setPage(1); load(1, '') }

  const submitReset = async () => {
    if (!selected || pwd.length < 8) return
    try {
      await authApi.adminResetPassword({ userId: selected.id, newPassword: pwd })
      message.success('密码已重置，目标用户旧 Token 已全局失效')
      setPwd('')
    } catch (e) { /* 拦截器已提示 */ }
  }

  const cols = [
    { title: 'ID', dataIndex: 'id', width: 70 },
    { title: '用户名', dataIndex: 'username', width: 160 },
    { title: '角色', dataIndex: 'role', width: 120, render: v => <Tag color={v === 'ROLE_ADMIN' ? 'red' : 'blue'}>{v}</Tag> },
    { title: '状态', dataIndex: 'userStatus', width: 100, render: v => <Tag color={v === 'ENABLED' ? 'green' : 'red'}>{v === 'ENABLED' ? '正常' : '已禁用'}</Tag> },
    { title: '注册时间', dataIndex: 'createTime', width: 180, render: v => v ? new Date(v).toLocaleString() : '-' },
    {
      title: '说明', render: (_, u) => u.role === 'ROLE_ADMIN'
        ? <span style={{ color: '#999', fontSize: 12 }}>管理员账号不可重置密码</span>
        : selected?.id === u.id ? <span style={{ color: '#67c23a', fontSize: 12 }}>已选择该用户</span> : null
    }
  ]

  return <div>
    <Typography.Title level={4} style={{ marginTop: 0, marginBottom: 16 }}>重置用户密码</Typography.Title>
    <Card>
      <Space style={{ marginBottom: 16 }}>
        <Input placeholder="用户名关键字" allowClear value={keyword} style={{ width: 220 }}
          onChange={e => setKeyword(e.target.value)} onPressEnter={search} />
        <Button type="primary" onClick={search}>查询</Button>
        <Button onClick={resetFilter}>重置</Button>
      </Space>
      <Table rowKey="id" dataSource={records} columns={cols} size="small" loading={loading}
        rowSelection={{
          type: 'radio',
          selectedRowKeys: selected ? [selected.id] : [],
          getCheckboxProps: u => ({ disabled: u.role === 'ROLE_ADMIN' }),
          onChange: (keys, rows) => setSelected(rows[0] || null)
        }}
        pagination={{ current: page, pageSize: 10, total, showSizeChanger: false, showTotal: t => `共 ${t} 条`,
          onChange: p => { setPage(p); load(p, keyword) } }} />
    </Card>
    <Card style={{ marginTop: 16, maxWidth: 720 }}>
      <div style={{ marginBottom: 12 }}>
        已选用户：{selected
          ? <span><strong>{selected.username}</strong>（ID: {selected.id}）</span>
          : <span style={{ color: '#999' }}>请先在上方列表中勾选一个普通用户</span>}
      </div>
      <Space>
        <Input.Password placeholder="新密码（至少8位）" value={pwd} disabled={!selected}
          onChange={e => setPwd(e.target.value)} style={{ width: 260 }} />
        <Button type="primary" disabled={!selected || pwd.length < 8} onClick={submitReset}>重置密码</Button>
      </Space>
      <p style={{ margin: '12px 0 0', fontSize: 12, color: '#8c8c8c' }}>重置后目标用户旧 Token 将全局失效，需重新登录。</p>
    </Card>
  </div>
}

// payment-demo-vue-admin/src/views/AdminResetPassword.vue
<template>
  <div>
    <h2 class="adm-page-title">重置用户密码</h2>
    <div class="adm-card">
      <div style="margin-bottom:16px">
        <el-input v-model="keyword" placeholder="用户名关键字" clearable size="small" style="width:220px;margin-right:8px" @keyup.enter.native="search" @clear="search"/>
        <el-button size="small" type="primary" @click="search">查询</el-button>
        <el-button size="small" @click="resetFilter">重置</el-button>
      </div>
      <el-table :data="records" v-loading="loading" size="small" style="width:100%">
        <el-table-column width="55" align="center">
          <template slot-scope="s">
            <el-radio v-model="selectedId" :label="s.row.id" :disabled="s.row.role==='ROLE_ADMIN'"><span></span></el-radio>
          </template>
        </el-table-column>
        <el-table-column prop="id" label="ID" width="70"/>
        <el-table-column prop="username" label="用户名" width="160"/>
        <el-table-column label="角色" width="120"><template slot-scope="s"><el-tag :type="s.row.role==='ROLE_ADMIN'?'danger':'primary'" size="mini">{{s.row.role}}</el-tag></template></el-table-column>
        <el-table-column label="状态" width="100"><template slot-scope="s"><el-tag :type="s.row.userStatus==='ENABLED'?'success':'danger'" size="mini">{{s.row.userStatus==='ENABLED'?'正常':'已禁用'}}</el-tag></template></el-table-column>
        <el-table-column label="注册时间" width="180"><template slot-scope="s">{{s.row.createTime?new Date(s.row.createTime).toLocaleString():'-'}}</template></el-table-column>
        <el-table-column label="说明" min-width="170">
          <template slot-scope="s">
            <span v-if="s.row.role==='ROLE_ADMIN'" style="color:#909399;font-size:12px">管理员账号不可重置密码</span>
            <span v-else-if="selectedId===s.row.id" style="color:#67c23a;font-size:12px">已选择该用户</span>
          </template>
        </el-table-column>
      </el-table>
      <el-pagination style="margin-top:16px;text-align:right" background layout="total, prev, pager, next"
        :current-page.sync="page" :page-size="10" :total="total" @current-change="load"/>
    </div>
    <div class="adm-card" style="margin-top:16px;max-width:720px">
      <div style="margin-bottom:12px">
        已选用户：
        <template v-if="selectedUser"><strong>{{selectedUser.username}}</strong>（ID: {{selectedUser.id}}）</template>
        <span v-else style="color:#909399">请先在上方列表中勾选一个普通用户</span>
      </div>
      <div style="display:flex;gap:12px;align-items:center">
        <el-input v-model="newPassword" type="password" show-password placeholder="新密码（至少8位）" style="width:260px" :disabled="!selectedUser"/>
        <el-button type="primary" :disabled="!selectedUser || newPassword.length<8" @click="submitReset">重置密码</el-button>
      </div>
      <p style="margin:12px 0 0;font-size:12px;color:#8C8C8C">重置后目标用户旧 Token 将全局失效，需重新登录。</p>
    </div>
  </div>
</template>
<script>
import authApi from '../api/auth'
export default {
  data() { return { records: [], total: 0, keyword: '', page: 1, loading: false, selectedId: null, selectedUser: null, newPassword: '' } },
  created() { this.load() },
  methods: {
    async load() {
      this.loading = true
      try {
        const params = { page: this.page, size: 10 }
        if (this.keyword.trim()) params.keyword = this.keyword.trim()
        const r = await authApi.adminUsers(params)
        this.records = (r.data && r.data.records) || []
        this.total = (r.data && r.data.total) || 0
      } catch (e) { /* 拦截器已提示 */ }
      finally { this.loading = false }
    },
    search() { this.page = 1; this.load() },
    resetFilter() { this.keyword = ''; this.page = 1; this.load() },
    async submitReset() {
      if (!this.selectedUser || this.newPassword.length < 8) return
      try {
        await authApi.resetPassword({ userId: this.selectedUser.id, newPassword: this.newPassword })
        this.$message.success('密码已重置，目标用户旧 Token 已全局失效')
        this.newPassword = ''
      } catch (e) { /* 拦截器已提示 */ }
    }
  },
  watch: {
    selectedId(val) {
      if (val == null) { this.selectedUser = null; return }
      this.selectedUser = this.records.find(u => u.id === val) || this.selectedUser
    }
  }
}
</script>
