// admin-ui/src/pages/Reconciliation.jsx
import { useCallback, useEffect, useState } from 'react'
import {
  Alert,
  Button,
  Card,
  Col,
  DatePicker,
  Drawer,
  Form,
  Input,
  message,
  Modal,
  Row,
  Select,
  Space,
  Statistic,
  Table,
  Tag,
  Tooltip,
  Typography,
  Upload
} from 'antd'
import {
  listDiscrepancies,
  listImports,
  listRecords,
  reconcileImport,
  resolveDiscrepancy,
  uploadBill
} from '@/api/reconciliation'

const { TextArea } = Input

const IMPORT_STATUS_COLOR = { IMPORTED: 'processing', RECONCILED: 'success', FAILED: 'error' }
const RECORD_TYPE_COLOR = { PAY: 'green', REFUND: 'orange' }
const DISCREPANCY_STATUS_COLOR = { OPEN: 'warning', RESOLVED: 'success' }
const BILL_KIND_COLOR = { ALL: 'geekblue', SUCCESS: 'green', REFUND: 'orange' }

const DISCREPANCY_TYPE_OPTIONS = [
  { value: 'PAY_CHANNEL_ONLY', label: '支付-渠道有本地无' },
  { value: 'PAY_LOCAL_ONLY', label: '支付-本地有渠道无' },
  { value: 'PAY_AMOUNT_MISMATCH', label: '支付-金额不一致' },
  { value: 'PAY_STATUS_MISMATCH', label: '支付-状态不一致' },
  { value: 'REFUND_CHANNEL_ONLY', label: '退款-渠道有本地无' },
  { value: 'REFUND_LOCAL_ONLY', label: '退款-本地有渠道无' },
  { value: 'REFUND_AMOUNT_MISMATCH', label: '退款-金额不一致' },
  { value: 'REFUND_STATUS_MISMATCH', label: '退款-状态不一致' }
]

const fen = (v) => (v === null || v === undefined ? '-' : `¥${(v / 100).toFixed(2)}`)

export default function Reconciliation() {
  const [queryDate, setQueryDate] = useState(null)
  const [importList, setImportList] = useState([])
  const [loading, setLoading] = useState(false)

  const [uploadDate, setUploadDate] = useState(null)
  const [fileList, setFileList] = useState([])
  const [uploading, setUploading] = useState(false)

  const [recordModalOpen, setRecordModalOpen] = useState(false)
  const [currentImport, setCurrentImport] = useState(null)
  const [recordList, setRecordList] = useState([])
  const [recordLoading, setRecordLoading] = useState(false)
  const [recordType, setRecordType] = useState('')

  const [discModalOpen, setDiscModalOpen] = useState(false)
  const [discList, setDiscList] = useState([])
  const [discLoading, setDiscLoading] = useState(false)
  const [discStatus, setDiscStatus] = useState('')
  const [discType, setDiscType] = useState('')

  const [resolveOpen, setResolveOpen] = useState(false)
  const [currentDisc, setCurrentDisc] = useState(null)
  const [resolveRemark, setResolveRemark] = useState('')
  const [resolving, setResolving] = useState(false)

  const loadImports = useCallback(() => {
    setLoading(true)
    const params = {}
    if (queryDate) {
      params.billDate = queryDate.format('YYYY-MM-DD')
    }
    listImports(params)
      .then((res) => {
        setImportList(res?.data || [])
      })
      .finally(() => {
        setLoading(false)
      })
  }, [queryDate])

  useEffect(() => {
    loadImports()
  }, [loadImports])

  const handleUpload = () => {
    if (!uploadDate) {
      message.warning('请选择账单日期')
      return
    }
    if (!fileList || fileList.length === 0) {
      message.warning('请选择微信交易账单 CSV 文件')
      return
    }
    const formData = new FormData()
    formData.append('file', fileList[0].originFileObj || fileList[0])
    formData.append('billDate', uploadDate.format('YYYY-MM-DD'))
    formData.append('billType', 'tradebill')
    setUploading(true)
    uploadBill(formData)
      .then((res) => {
        const data = res?.data
        if (data?.status === 'FAILED') {
          message.warning(`对账失败：${data.errorMessage || '未知原因'}`)
        } else if (data?.discrepancyCount > 0) {
          message.success(`上传成功，发现 ${data.discrepancyCount} 笔差异，请查看差异列表`)
        } else {
          message.success(res?.message || '上传并对账完成，无差异')
        }
        setFileList([])
        loadImports()
      })
      .finally(() => {
        setUploading(false)
      })
  }

  const openRecords = (row) => {
    setCurrentImport(row)
    setRecordType('')
    setRecordModalOpen(true)
  }

  const loadRecords = useCallback(() => {
    if (!currentImport) return
    setRecordLoading(true)
    const params = {}
    if (recordType) {
      params.recordType = recordType
    }
    listRecords(currentImport.importNo, params)
      .then((res) => {
        setRecordList(res?.data || [])
      })
      .finally(() => {
        setRecordLoading(false)
      })
  }, [currentImport, recordType])

  useEffect(() => {
    if (recordModalOpen) {
      loadRecords()
    }
  }, [recordModalOpen, loadRecords])

  const openDisc = (row) => {
    setCurrentImport(row)
    setDiscStatus('')
    setDiscType('')
    setDiscModalOpen(true)
  }

  const loadDisc = useCallback(() => {
    if (!currentImport) return
    setDiscLoading(true)
    const params = {}
    if (discStatus) {
      params.status = discStatus
    }
    if (discType) {
      params.discrepancyType = discType
    }
    listDiscrepancies(currentImport.importNo, params)
      .then((res) => {
        setDiscList(res?.data || [])
      })
      .finally(() => {
        setDiscLoading(false)
      })
  }, [currentImport, discStatus, discType])

  useEffect(() => {
    if (discModalOpen) {
      loadDisc()
    }
  }, [discModalOpen, loadDisc])

  const handleReconcile = (row) => {
    Modal.confirm({
      title: '确认重新对账',
      content: `确定要对批次 ${row.importNo}（账单日期 ${row.billDate}）重新执行对账吗？已对账批次将直接返回现有结果。`,
      okText: '确认',
      cancelText: '取消',
      onOk: () =>
        reconcileImport(row.importNo).then((res) => {
          message.success(res?.message || '对账完成')
          loadImports()
        })
    })
  }

  const openResolve = (row) => {
    setCurrentDisc(row)
    setResolveRemark('')
    setResolveOpen(true)
  }

  const handleResolve = () => {
    if (!resolveRemark.trim()) {
      message.warning('请填写处理备注')
      return
    }
    setResolving(true)
    resolveDiscrepancy(currentDisc.id, resolveRemark.trim())
      .then(() => {
        message.success('差异单已标记处理')
        setResolveOpen(false)
        loadDisc()
        loadImports()
      })
      .finally(() => {
        setResolving(false)
      })
  }

  const stats = {
    total: importList.length,
    reconciled: importList.filter((i) => i.status === 'RECONCILED').length,
    failed: importList.filter((i) => i.status === 'FAILED').length,
    discrepancies: importList.reduce((s, i) => s + (i.discrepancyCount || 0), 0)
  }

  const importColumns = [
    { title: '批次号', dataIndex: 'importNo', width: 180 },
    { title: '账单日期', dataIndex: 'billDate', width: 110 },
    {
      title: '账单种类',
      dataIndex: 'billKind',
      width: 110,
      render: (kind, row) => (
        <Tag color={BILL_KIND_COLOR[kind] || 'default'}>{row.billKindText || kind}</Tag>
      )
    },
    {
      title: '文件名',
      dataIndex: 'fileName',
      width: 200,
      ellipsis: true,
      render: (v) => (
        <Tooltip title={v}>
          <span>{v}</span>
        </Tooltip>
      )
    },
    { title: '支付笔数', dataIndex: 'payRecordCount', width: 90, align: 'center' },
    { title: '退款笔数', dataIndex: 'refundRecordCount', width: 90, align: 'center' },
    { title: '坏行', dataIndex: 'badLineCount', width: 70, align: 'center' },
    { title: '已匹配', dataIndex: 'matchedCount', width: 80, align: 'center' },
    {
      title: '差异数',
      dataIndex: 'discrepancyCount',
      width: 80,
      align: 'center',
      render: (v) => (v > 0 ? <Tag color="red">{v}</Tag> : <Tag color="green">0</Tag>)
    },
    {
      title: '状态',
      dataIndex: 'status',
      width: 100,
      render: (status, row) => (
        <Tooltip title={status === 'FAILED' ? row.errorMessage : ''}>
          <Tag color={IMPORT_STATUS_COLOR[status] || 'default'}>{row.statusText || status}</Tag>
        </Tooltip>
      )
    },
    { title: '导入时间', dataIndex: 'createTime', width: 170 },
    {
      title: '操作',
      width: 220,
      align: 'center',
      fixed: 'right',
      render: (_, row) => (
        <Space size="small" wrap>
          <Button type="link" size="small" onClick={() => openRecords(row)}>
            账单流水
          </Button>
          <Button type="link" size="small" onClick={() => openDisc(row)}>
            差异列表
          </Button>
          <Button type="link" size="small" onClick={() => handleReconcile(row)}>
            重新对账
          </Button>
        </Space>
      )
    }
  ]

  const recordColumns = [
    {
      title: '类型',
      dataIndex: 'recordType',
      width: 90,
      render: (t, row) => <Tag color={RECORD_TYPE_COLOR[t] || 'default'}>{row.recordTypeText || t}</Tag>
    },
    { title: '业务单号', dataIndex: 'bizNo', width: 200 },
    { title: '渠道流水号', dataIndex: 'channelSerialNo', width: 220 },
    { title: '交易类型', dataIndex: 'tradeType', width: 120 },
    { title: '交易状态', dataIndex: 'tradeStatus', width: 110 },
    {
      title: '支付金额',
      dataIndex: 'totalAmount',
      width: 110,
      render: (v, row) => (row.recordType === 'PAY' ? fen(v) : '-')
    },
    {
      title: '退款金额',
      dataIndex: 'refundAmount',
      width: 110,
      render: (v, row) => (row.recordType === 'REFUND' ? fen(v) : '-')
    },
    {
      title: '交易/退款时间',
      width: 170,
      render: (_, row) => row.recordType === 'REFUND' ? row.refundSuccessTime || row.refundApplyTime || '-' : row.tradeTime || '-'
    }
  ]

  const discColumns = [
    {
      title: '差异类型',
      dataIndex: 'discrepancyType',
      width: 170,
      render: (t, row) => <Tag color="red">{row.discrepancyTypeText || t}</Tag>
    },
    {
      title: '业务类型',
      dataIndex: 'bizType',
      width: 90,
      render: (t, row) => <Tag color={RECORD_TYPE_COLOR[t] || 'default'}>{row.bizTypeText || t}</Tag>
    },
    { title: '业务单号', dataIndex: 'bizNo', width: 200 },
    { title: '渠道流水号', dataIndex: 'channelSerialNo', width: 200 },
    { title: '渠道金额', dataIndex: 'channelAmount', width: 110, render: fen },
    { title: '本地金额', dataIndex: 'localAmount', width: 110, render: fen },
    { title: '渠道状态', dataIndex: 'channelStatus', width: 110, render: (v) => v || '-' },
    { title: '本地状态', dataIndex: 'localStatus', width: 110, render: (v) => v || '-' },
    {
      title: '处理状态',
      dataIndex: 'status',
      width: 100,
      render: (s, row) => <Tag color={DISCREPANCY_STATUS_COLOR[s] || 'default'}>{row.statusText || s}</Tag>
    },
    { title: '处理备注', dataIndex: 'resolveRemark', width: 160, ellipsis: true, render: (v) => v || '-' },
    { title: '处理人', dataIndex: 'resolvedBy', width: 100, render: (v) => v || '-' },
    { title: '处理时间', dataIndex: 'resolvedTime', width: 170, render: (v) => v || '-' },
    {
      title: '操作',
      width: 90,
      align: 'center',
      fixed: 'right',
      render: (_, row) =>
        row.status === 'OPEN' ? (
          <Button type="link" size="small" onClick={() => openResolve(row)}>
            标记处理
          </Button>
        ) : (
          '-'
        )
    }
  ]

  return (
    <div>
      <Typography.Title level={4} style={{ marginTop: 0, marginBottom: 16 }}>对账管理</Typography.Title>

        <Card style={{ marginBottom: 16 }}>
          <Alert
            type="info"
            showIcon
            style={{ marginBottom: 16 }}
            message="上传微信交易账单（CSV）后自动完成支付记录与退款记录对账"
            description="支持微信支付商户平台下载的三种交易账单：ALL（全部账单，含支付与退款）、SUCCESS（支付成功账单）、REFUND（退款账单），系统按表头自动识别，无需固定文件名。上传 ALL 一次完成双向对账；也可同一账单日分别上传 SUCCESS 与 REFUND，各自对支付、退款方向对账。同一文件重复上传自动返回原批次（幂等）；同一账单日同种类账单不可重复上传，ALL 与 SUCCESS/REFUND 互斥。"
          />
          <Space wrap size="large">
            <Form layout="inline">
              <Form.Item label="账单日期" required>
                <DatePicker
                  value={uploadDate}
                  onChange={(d) => setUploadDate(d)}
                  disabledDate={(current) => current && current.isAfter(new Date(), 'day')}
                  allowClear={false}
                />
              </Form.Item>
              <Form.Item label="账单文件" required>
                <Upload
                  accept=".csv"
                  maxCount={1}
                  fileList={fileList}
                  beforeUpload={() => false}
                  onRemove={() => setFileList([])}
                  onChange={({ fileList: list }) => setFileList(list.slice(-1))}
                >
                  <Button>选择 CSV 文件</Button>
                </Upload>
              </Form.Item>
              <Form.Item>
                <Button type="primary" loading={uploading} onClick={handleUpload}>
                  上传并对账
                </Button>
              </Form.Item>
            </Form>
          </Space>
        </Card>

        <Row gutter={16} style={{ marginBottom: 16 }}>
          <Col span={6}>
            <Card>
              <Statistic title="导入批次总数" value={stats.total} />
            </Card>
          </Col>
          <Col span={6}>
            <Card>
              <Statistic title="已对账批次" value={stats.reconciled} valueStyle={{ color: '#3f8600' }} />
            </Card>
          </Col>
          <Col span={6}>
            <Card>
              <Statistic title="对账失败批次" value={stats.failed} valueStyle={{ color: '#cf1322' }} />
            </Card>
          </Col>
          <Col span={6}>
            <Card>
              <Statistic title="差异总数" value={stats.discrepancies} valueStyle={{ color: '#fa8c16' }} />
            </Card>
          </Col>
        </Row>

        <Card style={{ marginBottom: 16 }}>
          <Space style={{ marginBottom: 16 }}>
            <span>账单日期：</span>
            <DatePicker
              value={queryDate}
              onChange={(d) => setQueryDate(d)}
              allowClear
              placeholder="按账单日期筛选"
            />
            <Button
              type="primary"
              onClick={() => {
                loadImports()
              }}
            >
              查询
            </Button>
            <Button
              onClick={() => {
                setQueryDate(null)
              }}
            >
              重置
            </Button>
          </Space>
          <Table
            rowKey="id"
            dataSource={importList}
            columns={importColumns}
            bordered
            loading={loading}
            scroll={{ x: 1500 }}
            size="middle"
            pagination={{ pageSize: 10, showSizeChanger: true, showTotal: (total) => `共 ${total} 条` }}
          />
        </Card>

      <Drawer
        title={`账单流水${currentImport ? ` - ${currentImport.importNo}（${currentImport.billDate}）` : ''}`}
        open={recordModalOpen}
        width={1100}
        onClose={() => setRecordModalOpen(false)}
        footer={<div style={{ textAlign: 'right' }}><Button onClick={() => setRecordModalOpen(false)}>关闭</Button></div>}
      >
        <Space style={{ marginBottom: 16 }}>
          <Select
            placeholder="记录类型"
            style={{ width: 140 }}
            allowClear
            value={recordType || undefined}
            onChange={(val) => setRecordType(val || '')}
          >
            <Select.Option value="PAY">支付</Select.Option>
            <Select.Option value="REFUND">退款</Select.Option>
          </Select>
        </Space>
        <Table
          rowKey="id"
          dataSource={recordList}
          columns={recordColumns}
          bordered
          loading={recordLoading}
          scroll={{ x: 1100 }}
          size="small"
          pagination={{ pageSize: 10, showSizeChanger: true, showTotal: (total) => `共 ${total} 条` }}
        />
      </Drawer>

      <Drawer
        title={`差异列表${currentImport ? ` - ${currentImport.importNo}（${currentImport.billDate}）` : ''}`}
        open={discModalOpen}
        width={1200}
        onClose={() => setDiscModalOpen(false)}
        footer={<div style={{ textAlign: 'right' }}><Button onClick={() => setDiscModalOpen(false)}>关闭</Button></div>}
      >
        <Space style={{ marginBottom: 16 }} wrap>
          <Select
            placeholder="处理状态"
            style={{ width: 140 }}
            allowClear
            value={discStatus || undefined}
            onChange={(val) => setDiscStatus(val || '')}
          >
            <Select.Option value="OPEN">待处理</Select.Option>
            <Select.Option value="RESOLVED">已处理</Select.Option>
          </Select>
          <Select
            placeholder="差异类型"
            style={{ width: 200 }}
            allowClear
            value={discType || undefined}
            onChange={(val) => setDiscType(val || '')}
            options={DISCREPANCY_TYPE_OPTIONS}
          />
        </Space>
        <Table
          rowKey="id"
          dataSource={discList}
          columns={discColumns}
          bordered
          loading={discLoading}
          scroll={{ x: 1500 }}
          size="small"
          pagination={{ pageSize: 10, showSizeChanger: true, showTotal: (total) => `共 ${total} 条` }}
        />
      </Drawer>

      <Modal
        title="标记差异已处理"
        open={resolveOpen}
        width={500}
        onCancel={() => setResolveOpen(false)}
        onOk={handleResolve}
        confirmLoading={resolving}
        okText="确认处理"
        cancelText="取消"
      >
        {currentDisc && (
          <div style={{ marginBottom: 12 }}>
            <p>
              差异类型：<Tag color="red">{currentDisc.discrepancyTypeText}</Tag>
              业务单号：<strong>{currentDisc.bizNo}</strong>
            </p>
          </div>
        )}
        <TextArea
          rows={4}
          value={resolveRemark}
          onChange={(e) => setResolveRemark(e.target.value)}
          placeholder="请输入差异处理说明（必填），如：已与渠道核对为跨日清算，差异关闭"
          maxLength={500}
        />
      </Modal>
    </div>
  )
}

// payment-demo-vue-admin/src/views/Reconciliation.vue
<template>
  <div>
    <h2 class="adm-page-title">对账管理</h2>

      <el-card shadow="never" style="margin-bottom:16px">
        <el-alert type="info" :closable="false" show-icon style="margin-bottom:16px"
          title="上传微信交易账单（CSV）后自动完成支付记录与退款记录对账"
          description="支持微信支付商户平台下载的三种交易账单：ALL（全部账单，含支付与退款）、SUCCESS（支付成功账单）、REFUND（退款账单），系统按表头自动识别，无需固定文件名。上传 ALL 一次完成双向对账；也可同一账单日分别上传 SUCCESS 与 REFUND，各自对支付、退款方向对账。同一文件重复上传自动返回原批次（幂等）；同一账单日同种类账单不可重复上传，ALL 与 SUCCESS/REFUND 互斥。" />
        <el-form :inline="true">
          <el-form-item label="账单日期" required>
            <el-date-picker v-model="uploadDate" type="date" value-format="yyyy-MM-dd"
              placeholder="选择账单日期" :picker-options="historyPickerOptions" />
          </el-form-item>
          <el-form-item label="账单文件" required>
            <el-upload action="#" :auto-upload="false" :limit="1" accept=".csv"
              :file-list="uploadFileList" :on-change="onFileChange" :on-remove="onFileRemove"
              :on-exceed="onFileExceed">
              <el-button size="small">选择 CSV 文件</el-button>
            </el-upload>
          </el-form-item>
          <el-form-item>
            <el-button type="primary" :loading="uploading" @click="handleUpload">上传并对账</el-button>
          </el-form-item>
        </el-form>
      </el-card>

      <el-row :gutter="16" style="margin-bottom:16px">
        <el-col :span="6"><el-card shadow="never"><div class="metric">导入批次<strong>{{imports.length}}</strong></div></el-card></el-col>
        <el-col :span="6"><el-card shadow="never"><div class="metric">已对账<strong style="color:#67c23a">{{reconciledCount}}</strong></div></el-card></el-col>
        <el-col :span="6"><el-card shadow="never"><div class="metric">对账失败<strong style="color:#f56c6c">{{failedCount}}</strong></div></el-card></el-col>
        <el-col :span="6"><el-card shadow="never"><div class="metric">差异总数<strong style="color:#e6a23c">{{discrepancyTotalCount}}</strong></div></el-card></el-col>
      </el-row>

      <el-card shadow="never">
        <el-form :inline="true">
          <el-form-item label="账单日期">
            <el-date-picker v-model="queryDate" type="date" value-format="yyyy-MM-dd"
              placeholder="按账单日期筛选" clearable />
          </el-form-item>
          <el-form-item>
            <el-button type="primary" @click="loadImports">查询</el-button>
            <el-button @click="queryDate=''">重置</el-button>
          </el-form-item>
        </el-form>
        <el-table :data="imports" border v-loading="loading">
          <el-table-column prop="importNo" label="批次号" width="180" />
          <el-table-column prop="billDate" label="账单日期" width="110" />
          <el-table-column label="账单种类" width="110">
            <template slot-scope="s">
              <el-tag :type="s.row.billKind === 'ALL' ? '' : (s.row.billKind === 'SUCCESS' ? 'success' : 'warning')" size="small">{{s.row.billKindText || s.row.billKind}}</el-tag>
            </template>
          </el-table-column>
          <el-table-column prop="fileName" label="文件名" min-width="180" show-overflow-tooltip />
          <el-table-column prop="payRecordCount" label="支付笔数" width="90" align="center" />
          <el-table-column prop="refundRecordCount" label="退款笔数" width="90" align="center" />
          <el-table-column prop="badLineCount" label="坏行" width="70" align="center" />
          <el-table-column prop="matchedCount" label="已匹配" width="80" align="center" />
          <el-table-column label="差异数" width="80" align="center">
            <template slot-scope="s">
              <el-tag :type="s.row.discrepancyCount > 0 ? 'danger' : 'success'" size="small">{{s.row.discrepancyCount || 0}}</el-tag>
            </template>
          </el-table-column>
          <el-table-column label="状态" width="110">
            <template slot-scope="s">
              <el-tooltip :content="s.row.status === 'FAILED' ? (s.row.errorMessage || '') : ''" placement="top" :disabled="s.row.status !== 'FAILED'">
                <el-tag :type="importTagType(s.row.status)" size="small">{{s.row.statusText || s.row.status}}</el-tag>
              </el-tooltip>
            </template>
          </el-table-column>
          <el-table-column prop="createTime" label="导入时间" width="170" />
          <el-table-column label="操作" width="230" align="center" fixed="right">
            <template slot-scope="s">
              <el-button type="text" @click="openRecords(s.row)">账单流水</el-button>
              <el-button type="text" @click="openDiscrepancies(s.row)">差异列表</el-button>
              <el-button type="text" @click="handleReconcile(s.row)">重新对账</el-button>
            </template>
          </el-table-column>
        </el-table>
      </el-card>

    <el-drawer :title="'账单流水' + (currentImport ? ' - ' + currentImport.importNo + '（' + currentImport.billDate + '）' : '')"
      :visible.sync="recordVisible" size="1100px" direction="rtl">
      <div style="margin-bottom:12px;padding:0 8px">
        <el-select v-model="recordFilter" clearable placeholder="记录类型" style="width:140px" @change="loadRecords">
          <el-option label="支付" value="PAY" />
          <el-option label="退款" value="REFUND" />
        </el-select>
      </div>
      <div style="padding:0 8px">
      <el-table :data="records" border v-loading="recordLoading" size="small">
        <el-table-column label="类型" width="90">
          <template slot-scope="s"><el-tag :type="s.row.recordType === 'PAY' ? 'success' : 'warning'" size="mini">{{s.row.recordTypeText || s.row.recordType}}</el-tag></template>
        </el-table-column>
        <el-table-column prop="bizNo" label="业务单号" min-width="190" show-overflow-tooltip />
        <el-table-column prop="channelSerialNo" label="渠道流水号" min-width="210" show-overflow-tooltip />
        <el-table-column prop="tradeType" label="交易类型" width="120" />
        <el-table-column prop="tradeStatus" label="交易状态" width="110" />
        <el-table-column label="支付金额" width="110">
          <template slot-scope="s">{{s.row.recordType === 'PAY' ? money(s.row.totalAmount) : '-'}}</template>
        </el-table-column>
        <el-table-column label="退款金额" width="110">
          <template slot-scope="s">{{s.row.recordType === 'REFUND' ? money(s.row.refundAmount) : '-'}}</template>
        </el-table-column>
        <el-table-column label="交易/退款时间" width="170">
          <template slot-scope="s">{{s.row.recordType === 'REFUND' ? (s.row.refundSuccessTime || s.row.refundApplyTime || '-') : (s.row.tradeTime || '-')}}</template>
        </el-table-column>
      </el-table>
      </div>
      <div slot="footer" style="text-align:right">
        <el-button @click="recordVisible=false">关闭</el-button>
      </div>
    </el-drawer>

    <el-drawer :title="'差异列表' + (currentImport ? ' - ' + currentImport.importNo + '（' + currentImport.billDate + '）' : '')"
      :visible.sync="discrepancyVisible" size="1200px" direction="rtl">
      <div style="margin-bottom:12px;padding:0 8px">
        <el-select v-model="discFilter.status" clearable placeholder="处理状态" style="width:140px" @change="loadDiscrepancies">
          <el-option label="待处理" value="OPEN" />
          <el-option label="已处理" value="RESOLVED" />
        </el-select>
        <el-select v-model="discFilter.discrepancyType" clearable placeholder="差异类型" style="width:200px;margin-left:8px" @change="loadDiscrepancies">
          <el-option v-for="t in discrepancyTypes" :key="t.value" :label="t.label" :value="t.value" />
        </el-select>
      </div>
      <div style="padding:0 8px">
      <el-table :data="discrepancies" border v-loading="discLoading" size="small">
        <el-table-column label="差异类型" width="170">
          <template slot-scope="s"><el-tag type="danger" size="mini">{{s.row.discrepancyTypeText || s.row.discrepancyType}}</el-tag></template>
        </el-table-column>
        <el-table-column label="业务类型" width="90">
          <template slot-scope="s"><el-tag :type="s.row.bizType === 'PAY' ? 'success' : 'warning'" size="mini">{{s.row.bizTypeText || s.row.bizType}}</el-tag></template>
        </el-table-column>
        <el-table-column prop="bizNo" label="业务单号" min-width="190" show-overflow-tooltip />
        <el-table-column prop="channelSerialNo" label="渠道流水号" min-width="190" show-overflow-tooltip />
        <el-table-column label="渠道金额" width="110"><template slot-scope="s">{{money(s.row.channelAmount)}}</template></el-table-column>
        <el-table-column label="本地金额" width="110"><template slot-scope="s">{{money(s.row.localAmount)}}</template></el-table-column>
        <el-table-column label="渠道状态" width="110"><template slot-scope="s">{{s.row.channelStatus || '-'}}</template></el-table-column>
        <el-table-column label="本地状态" width="110"><template slot-scope="s">{{s.row.localStatus || '-'}}</template></el-table-column>
        <el-table-column label="处理状态" width="100">
          <template slot-scope="s"><el-tag :type="s.row.status === 'OPEN' ? 'warning' : 'success'" size="mini">{{s.row.statusText || s.row.status}}</el-tag></template>
        </el-table-column>
        <el-table-column prop="resolveRemark" label="处理备注" min-width="150" show-overflow-tooltip>
          <template slot-scope="s">{{s.row.resolveRemark || '-'}}</template>
        </el-table-column>
        <el-table-column prop="resolvedBy" label="处理人" width="100"><template slot-scope="s">{{s.row.resolvedBy || '-'}}</template></el-table-column>
        <el-table-column prop="resolvedTime" label="处理时间" width="170"><template slot-scope="s">{{s.row.resolvedTime || '-'}}</template></el-table-column>
        <el-table-column label="操作" width="90" align="center" fixed="right">
          <template slot-scope="s">
            <el-button v-if="s.row.status === 'OPEN'" type="text" @click="openResolve(s.row)">标记处理</el-button>
            <span v-else>-</span>
          </template>
        </el-table-column>
      </el-table>
      </div>
      <div slot="footer" style="text-align:right">
        <el-button @click="discrepancyVisible=false">关闭</el-button>
      </div>
    </el-drawer>

    <el-dialog title="标记差异已处理" :visible.sync="resolveVisible" width="500px">
      <p v-if="resolveRow">差异类型：<el-tag type="danger" size="mini">{{resolveRow.discrepancyTypeText}}</el-tag>
        业务单号：<strong>{{resolveRow.bizNo}}</strong></p>
      <el-input v-model.trim="resolveRemark" type="textarea" :rows="4" maxlength="500" show-word-limit
        placeholder="请输入差异处理说明（必填），如：已与渠道核对为跨日清算，差异关闭" />
      <span slot="footer">
        <el-button @click="resolveVisible=false">取消</el-button>
        <el-button type="primary" :loading="resolving" @click="handleResolve">确认处理</el-button>
      </span>
    </el-dialog>
  </div>
</template>

<script>
import api from '../api/reconciliation'

export default {
  name: 'Reconciliation',
  data () {
    return {
      historyPickerOptions: {
        disabledDate (time) { return time.getTime() > Date.now() }
      },
      discrepancyTypes: [
        { value: 'PAY_CHANNEL_ONLY', label: '支付-渠道有本地无' },
        { value: 'PAY_LOCAL_ONLY', label: '支付-本地有渠道无' },
        { value: 'PAY_AMOUNT_MISMATCH', label: '支付-金额不一致' },
        { value: 'PAY_STATUS_MISMATCH', label: '支付-状态不一致' },
        { value: 'REFUND_CHANNEL_ONLY', label: '退款-渠道有本地无' },
        { value: 'REFUND_LOCAL_ONLY', label: '退款-本地有渠道无' },
        { value: 'REFUND_AMOUNT_MISMATCH', label: '退款-金额不一致' },
        { value: 'REFUND_STATUS_MISMATCH', label: '退款-状态不一致' }
      ],
      queryDate: '',
      imports: [],
      loading: false,
      uploadDate: '',
      uploadFile: null,
      uploadFileList: [],
      uploading: false,
      recordVisible: false,
      currentImport: null,
      records: [],
      recordLoading: false,
      recordFilter: '',
      discrepancyVisible: false,
      discrepancies: [],
      discLoading: false,
      discFilter: { status: '', discrepancyType: '' },
      resolveVisible: false,
      resolveRow: null,
      resolveRemark: '',
      resolving: false
    }
  },
  computed: {
    reconciledCount () { return this.imports.filter(i => i.status === 'RECONCILED').length },
    failedCount () { return this.imports.filter(i => i.status === 'FAILED').length },
    discrepancyTotalCount () { return this.imports.reduce((s, i) => s + (i.discrepancyCount || 0), 0) }
  },
  created () { this.loadImports() },
  methods: {
    money (v) { return (v === null || v === undefined) ? '-' : (Number(v) / 100).toFixed(2) },
    importTagType (status) {
      return status === 'RECONCILED' ? 'success' : status === 'FAILED' ? 'danger' : 'info'
    },
    async loadImports () {
      this.loading = true
      try {
        const params = {}
        if (this.queryDate) params.billDate = this.queryDate
        const r = await api.listImports(params)
        this.imports = r.data || []
      } finally {
        this.loading = false
      }
    },
    onFileChange (file, fileList) {
      this.uploadFile = file.raw
      this.uploadFileList = fileList.slice(-1)
    },
    onFileRemove () {
      this.uploadFile = null
      this.uploadFileList = []
    },
    onFileExceed (files) {
      this.uploadFile = files[0]
      this.uploadFileList = [{ name: files[0].name, raw: files[0] }]
    },
    async handleUpload () {
      if (!this.uploadDate) return this.$message.warning('请选择账单日期')
      if (!this.uploadFile) return this.$message.warning('请选择微信交易账单 CSV 文件')
      const formData = new FormData()
      formData.append('file', this.uploadFile)
      formData.append('billDate', this.uploadDate)
      formData.append('billType', 'tradebill')
      this.uploading = true
      try {
        const r = await api.uploadBill(formData)
        const data = r.data || {}
        if (data.status === 'FAILED') {
          this.$message.warning('对账失败：' + (data.errorMessage || '未知原因'))
        } else if (data.discrepancyCount > 0) {
          this.$message.success('上传成功，发现 ' + data.discrepancyCount + ' 笔差异，请查看差异列表')
        } else {
          this.$message.success(r.message || '上传并对账完成，无差异')
        }
        this.uploadFile = null
        this.uploadFileList = []
        this.loadImports()
      } finally {
        this.uploading = false
      }
    },
    openRecords (row) {
      this.currentImport = row
      this.recordFilter = ''
      this.records = []
      this.recordVisible = true
      this.loadRecords()
    },
    async loadRecords () {
      if (!this.currentImport) return
      this.recordLoading = true
      try {
        const params = {}
        if (this.recordFilter) params.recordType = this.recordFilter
        const r = await api.listRecords(this.currentImport.importNo, params)
        this.records = r.data || []
      } finally {
        this.recordLoading = false
      }
    },
    openDiscrepancies (row) {
      this.currentImport = row
      this.discFilter = { status: '', discrepancyType: '' }
      this.discrepancies = []
      this.discrepancyVisible = true
      this.loadDiscrepancies()
    },
    async loadDiscrepancies () {
      if (!this.currentImport) return
      this.discLoading = true
      try {
        const params = {}
        if (this.discFilter.status) params.status = this.discFilter.status
        if (this.discFilter.discrepancyType) params.discrepancyType = this.discFilter.discrepancyType
        const r = await api.listDiscrepancies(this.currentImport.importNo, params)
        this.discrepancies = r.data || []
      } finally {
        this.discLoading = false
      }
    },
    handleReconcile (row) {
      this.$confirm('确定要对批次 ' + row.importNo + '（账单日期 ' + row.billDate + '）重新执行对账吗？已对账批次将直接返回现有结果。', '确认重新对账', {
        confirmButtonText: '确认', cancelButtonText: '取消', type: 'warning'
      }).then(async () => {
        const r = await api.reconcile(row.importNo)
        this.$message.success(r.message || '对账完成')
        this.loadImports()
      }).catch(() => {})
    },
    openResolve (row) {
      this.resolveRow = row
      this.resolveRemark = ''
      this.resolveVisible = true
    },
    async handleResolve () {
      if (!this.resolveRemark) return this.$message.warning('请填写处理备注')
      this.resolving = true
      try {
        await api.resolveDiscrepancy(this.resolveRow.id, { resolveRemark: this.resolveRemark })
        this.$message.success('差异单已标记处理')
        this.resolveVisible = false
        this.loadDiscrepancies()
        this.loadImports()
      } finally {
        this.resolving = false
      }
    }
  }
}
</script>

<style scoped>
.metric { text-align: center; color: #666 }
.metric strong { display: block; font-size: 26px; color: #303133; margin-top: 8px }
</style>
