// admin-ui/src/pages/UserList.jsx
import { useEffect, useState } from 'react'
import { Button, Card, Descriptions, Drawer, Input, Modal, Space, Spin, Table, Tag, message, Typography } from 'antd'
import authApi from '@/api/auth'

export default function UserList() {
  const [records, setRecords] = useState([])
  const [total, setTotal] = useState(0)
  const [keyword, setKeyword] = useState('')
  const [page, setPage] = useState(1)
  const [loading, setLoading] = useState(false)
  const [detailId, setDetailId] = useState(null)
  const [detail, setDetail] = useState(null)
  const [detailLoading, setDetailLoading] = useState(false)
  const [resetPwd, setResetPwd] = useState('')

  const load = async (p = page, kw = keyword) => {
    setLoading(true)
    try {
      const params = { page: p, size: 10 }
      if (kw.trim()) params.keyword = kw.trim()
      const r = await authApi.adminUsers(params)
      setRecords((r.data && r.data.records) || [])
      setTotal((r.data && r.data.total) || 0)
    } catch (e) { /* 拦截器已提示 */ }
    finally { setLoading(false) }
  }
  useEffect(() => { load() }, [])
  useEffect(() => {
    if (detailId == null) { setDetail(null); return }
    setDetailLoading(true); setDetail(null); setResetPwd('')
    authApi.adminUserDetail(detailId)
      .then(r => setDetail(r.data))
      .catch(() => { /* 拦截器已提示 */ })
      .finally(() => setDetailLoading(false))
  }, [detailId])

  const search = () => { setPage(1); load(1, keyword) }
  const reset = () => { setKeyword(''); setPage(1); load(1, '') }

  const submitReset = async () => {
    if (!resetPwd || resetPwd.length < 8) return message.error('新密码至少 8 位')
    try {
      await authApi.adminResetPassword({ userId: detail.id, newPassword: resetPwd })
      message.success('密码已重置，该用户旧 Token 已失效，登录锁定已解除')
      setResetPwd('')
    } catch (e) { message.error(e?.response?.data?.message || '重置失败') }
  }

  const toggleStatus = (u) => {
    const target = u.userStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED'
    const doSet = async () => {
      try {
        await authApi.setUserStatus(u.id, target)
        message.success(target === 'DISABLED' ? '已禁用，该用户已被强制下线' : '已启用')
        load()
        if (detail && detail.id === u.id) setDetailId(u.id)
      } catch (e) { /* 拦截器已提示 */ }
    }
    if (target === 'DISABLED') {
      Modal.confirm({ title: `禁用用户 - ${u.username}`, content: '禁用后该用户将被强制下线且无法登录，确认操作？', okText: '禁用', okButtonProps: { danger: true }, onOk: doSet })
    } else { doSet() }
  }

  const cols = [
    { title: 'ID', dataIndex: 'id', width: 70 },
    { title: '用户名', dataIndex: 'username', width: 160, render: (t, u) => <a onClick={() => setDetailId(u.id)}>{t}</a> },
    { title: '角色', dataIndex: 'role', width: 120, render: v => <Tag color={v === 'ROLE_ADMIN' ? 'red' : 'blue'}>{v}</Tag> },
    { title: '状态', dataIndex: 'userStatus', width: 100, render: v => <Tag color={v === 'ENABLED' ? 'green' : 'red'}>{v === 'ENABLED' ? '正常' : '已禁用'}</Tag> },
    { title: '注册时间', dataIndex: 'createTime', width: 180, render: v => v ? new Date(v).toLocaleString() : '-' },
    {
      title: '操作', width: 200, render: (_, u) => u.role !== 'ROLE_ADMIN' ? (
        <Space>
          <Button size="small" onClick={() => setDetailId(u.id)}>详情/重置密码</Button>
          {u.userStatus === 'ENABLED'
            ? <Button danger size="small" onClick={() => toggleStatus(u)}>禁用</Button>
            : <Button size="small" type="primary" onClick={() => toggleStatus(u)}>启用</Button>}
        </Space>
      ) : <span style={{ color: '#999' }}>-</span>
    }
  ]

  return (
    <div>
      <Typography.Title level={4} style={{ marginTop: 0, marginBottom: 16 }}>用户列表</Typography.Title>
      <Card>
      <Space style={{ marginBottom: 16 }}>
        <Input placeholder="用户名关键字" allowClear value={keyword} style={{ width: 220 }}
          onChange={e => setKeyword(e.target.value)} onPressEnter={search} />
        <Button type="primary" onClick={search}>查询</Button>
        <Button onClick={reset}>重置</Button>
      </Space>
      <Table rowKey="id" dataSource={records} columns={cols} size="small" loading={loading}
        pagination={{ current: page, pageSize: 10, total, showSizeChanger: false, showTotal: t => `共 ${t} 条`,
          onChange: p => { setPage(p); load(p, keyword) } }} />
      <Drawer open={detailId != null} width={560} onClose={() => setDetailId(null)} title={detail ? `用户详情 - ${detail.username}` : '用户详情'}>
        {detailLoading || !detail ? <Spin style={{ display: 'block', margin: '80px auto' }} /> : (
          <div>
            <Descriptions column={1} bordered>
              <Descriptions.Item label="ID">{detail.id}</Descriptions.Item>
              <Descriptions.Item label="用户名">{detail.username}</Descriptions.Item>
              <Descriptions.Item label="角色"><Tag color={detail.role === 'ROLE_ADMIN' ? 'red' : 'blue'}>{detail.role}</Tag></Descriptions.Item>
              <Descriptions.Item label="状态"><Tag color={detail.userStatus === 'ENABLED' ? 'green' : 'red'}>{detail.userStatus === 'ENABLED' ? '正常' : '已禁用'}</Tag></Descriptions.Item>
              <Descriptions.Item label="在线状态">{detail.online ? <Tag color="green">在线</Tag> : <Tag>离线</Tag>}</Descriptions.Item>
              <Descriptions.Item label="注册时间">{detail.createTime ? new Date(detail.createTime).toLocaleString() : '-'}</Descriptions.Item>
              <Descriptions.Item label="更新时间">{detail.updateTime ? new Date(detail.updateTime).toLocaleString() : '-'}</Descriptions.Item>
            </Descriptions>
            {detail.role !== 'ROLE_ADMIN' && (
              <div style={{ marginTop: 20 }}>
                <h4>重置密码</h4>
                <Space style={{ width: '100%' }}>
                  <Input.Password value={resetPwd} onChange={e => setResetPwd(e.target.value)} placeholder="新密码（至少 8 位）" style={{ width: 280 }} />
                  <Button type="primary" onClick={submitReset}>重置密码</Button>
                </Space>
                <p style={{ fontSize: 12, color: '#8c8c8c', marginTop: 8 }}>重置后该用户旧 Token 全局失效，需重新登录。</p>
              </div>
            )}
          </div>
        )}
      </Drawer>
      </Card>
    </div>
  )
}

// payment-demo-vue-admin/src/views/UserList.vue
<template>
  <div>
    <h2 class="adm-page-title">用户列表</h2>
    <div class="adm-card">
    <div style="margin-bottom:16px">
      <el-input v-model="keyword" placeholder="用户名关键字" clearable size="small" style="width:220px;margin-right:8px" @keyup.enter.native="search" @clear="search"/>
      <el-button size="small" type="primary" @click="search">查询</el-button>
      <el-button size="small" @click="reset">重置</el-button>
    </div>
    <el-table :data="records" v-loading="loading" size="small" style="width:100%">
      <el-table-column prop="id" label="ID" width="70"/>
      <el-table-column label="用户名" width="160"><template slot-scope="s"><a @click="openDetail(s.row)" style="cursor:pointer;color:#409eff">{{s.row.username}}</a></template></el-table-column>
      <el-table-column label="角色" width="120"><template slot-scope="s"><el-tag :type="s.row.role==='ROLE_ADMIN'?'danger':'primary'" size="mini">{{s.row.role}}</el-tag></template></el-table-column>
      <el-table-column label="状态" width="100"><template slot-scope="s"><el-tag :type="s.row.userStatus==='ENABLED'?'success':'danger'" size="mini">{{s.row.userStatus==='ENABLED'?'正常':'已禁用'}}</el-tag></template></el-table-column>
      <el-table-column label="注册时间" width="180"><template slot-scope="s">{{s.row.createTime?new Date(s.row.createTime).toLocaleString():'-'}}</template></el-table-column>
      <el-table-column label="操作" width="220">
        <template slot-scope="s">
          <template v-if="s.row.role!=='ROLE_ADMIN'">
            <el-button size="mini" @click="openDetail(s.row)">详情/重置密码</el-button>
            <el-button v-if="s.row.userStatus==='ENABLED'" size="mini" type="danger" @click="toggleStatus(s.row)">禁用</el-button>
            <el-button v-else size="mini" type="primary" @click="toggleStatus(s.row)">启用</el-button>
          </template>
          <span v-else style="color:#999">-</span>
        </template>
      </el-table-column>
    </el-table>
    <el-pagination style="margin-top:16px;text-align:right" background layout="total, prev, pager, next"
      :current-page.sync="page" :page-size="10" :total="total" @current-change="load"/>
    </div>
    <el-drawer :title="detail.id ? '用户详情 - ' + detail.username : '用户详情'" :visible.sync="detailVisible" size="560px" direction="rtl">
      <div v-loading="detailLoading" style="padding:0 8px">
        <el-descriptions :column="1" border>
          <el-descriptions-item label="ID">{{detail.id}}</el-descriptions-item>
          <el-descriptions-item label="用户名">{{detail.username}}</el-descriptions-item>
          <el-descriptions-item label="角色"><el-tag :type="detail.role==='ROLE_ADMIN'?'danger':'primary'" size="small">{{detail.role}}</el-tag></el-descriptions-item>
          <el-descriptions-item label="状态"><el-tag :type="detail.userStatus==='ENABLED'?'success':'danger'" size="small">{{detail.userStatus==='ENABLED'?'正常':'已禁用'}}</el-tag></el-descriptions-item>
          <el-descriptions-item label="在线状态"><el-tag :type="detail.online?'success':'info'" size="small">{{detail.online?'在线':'离线'}}</el-tag></el-descriptions-item>
          <el-descriptions-item label="注册时间">{{detail.createTime?new Date(detail.createTime).toLocaleString():'-'}}</el-descriptions-item>
          <el-descriptions-item label="更新时间">{{detail.updateTime?new Date(detail.updateTime).toLocaleString():'-'}}</el-descriptions-item>
        </el-descriptions>
        <div v-if="detail.role && detail.role!=='ROLE_ADMIN'" style="margin-top:20px">
          <h4>重置密码</h4>
          <div style="display:flex;gap:8px">
            <el-input v-model="resetPwd" type="password" show-password placeholder="新密码（至少 8 位）" style="width:280px"/>
            <el-button type="primary" @click="submitReset">重置密码</el-button>
          </div>
          <p style="font-size:12px;color:#909399;margin-top:8px">重置后该用户旧 Token 全局失效，需重新登录。</p>
        </div>
      </div>
    </el-drawer>
  </div>
</template>

<script>
import authApi from '../api/auth'
export default {
  data() { return { records: [], total: 0, keyword: '', page: 1, loading: false, detailVisible: false, detailLoading: false, detail: {}, resetPwd: '' } },
  created() { this.load() },
  methods: {
    async load() {
      this.loading = true
      try {
        const params = { page: this.page, size: 10 }
        if (this.keyword.trim()) params.keyword = this.keyword.trim()
        const r = await authApi.adminUsers(params)
        this.records = (r.data && r.data.records) || []
        this.total = (r.data && r.data.total) || 0
      } catch (e) { /* 拦截器已提示 */ }
      finally { this.loading = false }
    },
    search() { this.page = 1; this.load() },
    reset() { this.keyword = ''; this.page = 1; this.load() },
    async openDetail(row) {
      this.detailVisible = true; this.detailLoading = true; this.detail = {}; this.resetPwd = ''
      try {
        const res = await authApi.adminUserDetail(row.id)
        this.detail = res.data || {}
      } catch (e) { /* 拦截器已提示 */ }
      finally { this.detailLoading = false }
    },
    async submitReset() {
      if (!this.resetPwd || this.resetPwd.length < 8) return this.$message.error('新密码至少 8 位')
      try {
        await authApi.resetPassword({ userId: this.detail.id, newPassword: this.resetPwd })
        this.$message.success('密码已重置，该用户旧 Token 已失效，登录锁定已解除')
        this.resetPwd = ''
      } catch (e) { this.$message.error('重置失败') }
    },
    async toggleStatus(row) {
      const target = row.userStatus === 'ENABLED' ? 'DISABLED' : 'ENABLED'
      const doSet = async () => {
        try {
          await authApi.setUserStatus(row.id, target)
          this.$message.success(target === 'DISABLED' ? '已禁用，该用户已被强制下线' : '已启用')
          this.load()
        } catch (e) { /* 拦截器已提示 */ }
      }
      if (target === 'DISABLED') {
        try { await this.$confirm('禁用后该用户将被强制下线且无法登录，确认操作？', '禁用用户 - ' + row.username, { type: 'warning' }); doSet() } catch (e) { /* 用户取消 */ }
      } else { doSet() }
    }
  }
}
</script>
